### ISSUE TITLE
launcher

### ISSUE THREAD

**Issue by lsy88** [go-rod/rod#1164]
Rod Version: v0.114.8

## The code to demonstrate your question

```go
l := launcher.New().
		Set("disable-blink-features", "AutomationControlled").
		Set("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36").
		Set("disable-default-apps").
		Set("no-sandbox", "true").
		Set("no-default-browser-check").
		Set("enable-privacy-sandbox-ads-apis", "false").
		Set("disable-web-security").
		Set("headless", "new").
		Set("no-first-run").
		Leakless(false)
	path, has := launcher.LookPath()
	if has {
		l = l.Bin(path)
	}
	return l
```

## What you got

```
panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /home/ubuntu/.cache/rod/browser/chromium-1131657/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


goroutine 30 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xfe5100?, 0xc00018c610?})
        C:/Users/li.sy/go/pkg/mod/github.com/go-rod/rod@v0.114.8/lib/utils/utils.go:69 +0x1d
github.com/go-rod/rod/lib/utils.E(...)
        C:/Users/li.sy/go/pkg/mod/github.com/go-rod/rod@v0.114.8/lib/utils/utils.go:75
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc00068fb08?)
        C:/Users/li.sy/go/pkg/mod/github.com/go-rod/rod@v0.114.8/lib/launcher/launcher.go:389 +0x62

```

## What you expect to see
我想在ubuntu上正常运行

**Comment by lsy88** [comment]
> 顾名思义，缺少动态库，安装相应的动态库就行

https://github.com/puppeteer/puppeteer/pull/5693 我是使用这个解决的
