### ISSUE TITLE
rod=trace,cdp may cause panic

### ISSUE THREAD

**Issue by NormalPunch** [go-rod/rod#120]
`*E` api may panic when trace cdp: 

```go
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"time"
)

func main() {

	page := rod.New().Connect().Page("about:blank")

	// run with env: rod=trace,cdp will cause panic
	_, err := page.Timeout(time.Second).ElementByJSE(page.Sleeper(), "", `() => document.querySelector("never-exists")`, nil)
	fmt.Println(err)

}

```

```
go run main.go
[2020-07-15 20:51:26] [trace] js () => document.querySelector("never-exists")(null)
panic: context deadline exceeded

goroutine 1 [running]:
github.com/go-rod/rod.CancelPanic(...)
        github.com/go-rod/rod@v0.45.1/utils.go:42
github.com/go-rod/rod.(*Page).Overlay(0xc000068000, 0x0, 0x0, 0x407f400000000000, 0x0, 0xc00011e000, 0x42, 0x30000)
        github.com/go-rod/rod@v0.45.1/dev_helpers.go:124 +0x53c
github.com/go-rod/rod.(*Page).tryTraceFn(0xc000068000, 0xccef15, 0x2c, 0x0, 0x0, 0x0, 0x60)
        github.com/go-rod/rod@v0.45.1/dev_helpers.go:180 +0x296
github.com/go-rod/rod.(*Page).ElementByJSE.func3(0x60, 0xc5a860, 0xf4f201)
        github.com/go-rod/rod@v0.45.1/query.go:128 +0xc3
github.com/ysmood/kit/pkg/utils.Retry(0xf4f2a0, 0xc000300420, 0xc000308980, 0xc000300480, 0xc000308980, 0xc0004c7ef0)
        github.com/ysmood/kit@v0.24.6/pkg/utils/sleeper.go:112 +0x2e
github.com/go-rod/rod.(*Page).ElementByJSE(0xc000068000, 0xc000308980, 0x0, 0x0, 0xccef15, 0x2c, 0x0, 0x0, 0x0, 0xc000024178, ...)
        github.com/go-rod/rod@v0.45.1/query.go:127 +0x184
main.main()
        main.go:15 +0xdf
exit status 2

```

**Comment by ysmood** [comment]
fixed in d2d1e8f6da2d1b4a5491fcb5d7eeb1a425b128b6
