### ISSUE TITLE
关于切换iframe后获取同一位置元素报错， 请问如何处理？

### ISSUE THREAD

**Issue by Abin01** [go-rod/rod#164]
main.go

```go
package main

import (
	"fmt"
	"path/filepath"

	"github.com/go-rod/bypass"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/cdp"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/ysmood/kit"
)

func main() {
	url1 := launcher.New().Headless(false).Launch()
	client := cdp.New(url1)
	browser := rod.New().Client(client).Connect()
	defer browser.Close()

	page := bypass.Page(browser).Window(0, 0, 1000, 1000)
	page.Navigate(srcFile("./click.html")).WaitLoad()
	page.ElementX(`/html/body/button[1]`).Click()
	fmt.Println(page.Search(`/html/body/div/span`).Text())
	kit.Sleep(1)
	page.ElementX(`/html/body/button[2]`).Click()
	kit.Sleep(1)
	fmt.Println(page.Search(`/html/body/div/span`).Text())
	select {}
}

func srcFile(path string) string {
	return "file://" + file(path)
}

var slash = filepath.FromSlash

// get abs file path from fixtures folder, return sample "/a/b/click.html"
func file(path string) string {
	f, err := filepath.Abs(slash(path))
	kit.E(err)
	return f
}`
click.html
`<html>
    <style>
        h4 {
            width: 200px;
            height: 30px;
        }
        button {
            margin: 100px;
        }
    </style>
    <body>
        <h4>Title</h4>
        <button onclick="document.getElementById('iframe').setAttribute('src','./iframe1.html')" >iframe1</button>
        <button onclick="document.getElementById('iframe').setAttribute('src','./iframe2.html')" >iframe2</button>

        <div><iframe id="iframe" src="" frameborder="0"></iframe></div>
    </body>
</html>
```

iframe1.html

```
<html>
    <body>
        <div>
            <span>hello I'm iframe1</span>
        </div>
    </body>
</html>
```
iframe2.html
```
<html>
    <body>
        <div>
            <span>hello I'm iframe2</span>
        </div>
    </body>
</html>
```

result

```
hello I'm iframe1
panic: {"code":-32000,"message":"Node with given id does not belong to the document","data":""}

goroutine 1 [running]:
github.com/ysmood/kit/pkg/utils.E(0xc0001fd230, 0x1, 0x1, 0x13, 0x0, 0x1)
	D:/Program Files/Gopath/src/github.com/ysmood/kit/pkg/utils/utils.go:33 +0xb2
github.com/go-rod/rod.(*Page).Search(0xc0000b6000, 0xccaa81, 0x13, 0x1)
	D:/Program Files/Gopath/src/github.com/go-rod/rod/sugar.go:357 +0x100
main.main()
	c:/Users/zhaob/Desktop/test/main.go:27 +0x33e
exit status 2
```

**Comment by ysmood** [comment]
可以用 `el.Frame` 函数试试，Search 还不是很稳定，可能是某种 bug。Frame 的用法搜索下单元测试就知道了

**Comment by ysmood** [comment]
你可以试试 v0.49.0 应该修复了这个bug

**Comment by Abin01** [comment]
昨天试了下 ifram（）方法也不行。 v0.49.0可以了，感谢
