### ISSUE TITLE
Hijacking under proxy with auth

### ISSUE THREAD

**Issue by Sadykov70** [go-rod/rod#186]
Hi guys, sorry for my english (and thanks to google translator)

Today I discovered your cool project (as for me it's much nicer than chromedp)
My main goal is to read the requests and responses without changing them.
I'm trying to figure out how I can hijack from a proxy with authorization. 

All that I managed to do with help of examples is this code:
```go
package main

import (
	"fmt"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"net/http"
	"net/url"
	"time"
)

func main() {
	ctrlUrl := launcher.New().
		Set("proxy-server", "1.2.3.4:8000").
		Delete("use-mock-keychain").
		Launch()

	browser := rod.New().ControlURL(ctrlUrl).Connect()
	defer browser.Close()

	router := browser.HijackRequests()
	defer router.Stop()

	router.Add("*", func(ctx *rod.Hijack) {
		proxy, _ := url.Parse("http://user:pass@1.2.3.4:8000")
		ctx.Request.SetClient(&http.Client{
			Transport: &http.Transport{
				Proxy: http.ProxyURL(proxy),
			},
			Timeout: 30 * time.Second,
		})

		fmt.Println(ctx.Request.Body())
		fmt.Println(ctx.Response.StringBody())

		ctx.LoadResponse()
	})

	go router.Run()

	browser.HandleAuth("user", "pass")

	page := browser.Timeout(time.Minute).Page(`https://api.ipify.org/?format=json`)
	page.WaitRequestIdle()
}
```

Output:
```shell
{"ip":"5.8.13.11"}
2020/08/13 16:22:39 [rod hijack err] {"code":-32602,"message":"Invalid InterceptionId.","data":""}

Process finished with exit code 0

```
Basically, `{"ip":"5.8.13.11"}` is what I need as a response body, but if I test the code on other sites, it can produce errors like:

```
panic: Get "https://www.google.com/": context canceled

goroutine 54 [running]:
github.com/go-rod/rod/lib/utils.E(...)
        /www/go-projects/src/github.com/go-rod/rod/lib/utils/main.go:14
github.com/go-rod/rod.(*HijackResponse).Body(0xc00024eb80, 0xc000010018, 0xc00004ad08, 0x1)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:437 +0x10a
github.com/go-rod/rod.(*HijackResponse).StringBody(...)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:459
main.main.func1(0xc0003fc6c0)
        /www/go-projects/src/tw_rod/main2.go:37 +0x184
github.com/go-rod/rod.(*HijackRouter).initEvents.func1.1(0xc000070050, 0xf9b300, 0xc000064000, 0xc0000c4180)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:65 +0x161
created by github.com/go-rod/rod.(*HijackRouter).initEvents.func1
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:61 +0x5a
```

Also, everything is working good without proxy

`go version go1.14.6 linux/amd64`

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/blob/3eaaae713b965b01ca7cc8fbe644393d88a6602c/examples_test.go#L235-L237

Have you read this example?

**Comment by ysmood** [comment]
`Set("proxy-server", "1.2.3.4:8000").` will conflict with `router.Add("*"`

Sorry, I can't understand what you want to achieve from your example code.

**Comment by ysmood** [comment]
[Describe the goal, not the step.](http://www.catb.org/~esr/faqs/smart-questions.html#goal)

**Comment by Sadykov70** [comment]
@ysmood Thanks for the answer

I've refactored my code according to your recommendations and added my proxy credentials
```go
func main() {
	ctrlUrl := launcher.New().
		Set("proxy-server", "5.8.15.168:8000").
		Delete("use-mock-keychain").
		Launch()

	browser := rod.New().ControlURL(ctrlUrl).Connect()
	defer browser.Close()

	browser.HandleAuth("tcjbNj", "RuPZAq")

	router := browser.HijackRequests()
	defer router.Stop()

	router.Add("*", func(ctx *rod.Hijack) {
		proxy, _ := url.Parse("http://tcjbNj:RuPZAq@5.8.15.168:8000")
		ctx.Request.SetClient(&http.Client{
			Transport: &http.Transport{
				Proxy: http.ProxyURL(proxy),
			},
			Timeout: time.Minute,
		})

		fmt.Println(ctx.Request.Body())
		fmt.Println(ctx.Response.StringBody())

		ctx.LoadResponse()
	})

	go router.Run()

	page := browser.Timeout(time.Minute).Page(`https://api.ipify.org/?format=json`)
	page.WaitRequestIdle()
}
```
Produces
```
panic: Get "https://api.ipify.org/?format=json": context canceled

goroutine 55 [running]:
github.com/go-rod/rod/lib/utils.E(...)
        /www/go-projects/src/github.com/go-rod/rod/lib/utils/main.go:14
github.com/go-rod/rod.(*HijackResponse).Body(0xc000388820, 0xc000010018, 0xc00004ad08, 0x1)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:437 +0x10a
github.com/go-rod/rod.(*HijackResponse).StringBody(...)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:459
main.main.func1(0xc0003834d0)
        /www/go-projects/src/tw_rod/main3.go:34 +0xae
github.com/go-rod/rod.(*HijackRouter).initEvents.func1.1(0xc000398280, 0xf9b2a0, 0xc00048c200, 0xc00038c200)
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:65 +0x161
created by github.com/go-rod/rod.(*HijackRouter).initEvents.func1
        /www/go-projects/src/github.com/go-rod/rod/hijack.go:61 +0x5a

Process finished with exit code 2

```

**Comment by ysmood** [comment]
Will reopen this issue once you provide the required info.

**Comment by h3isenbug** [comment]
Hi
I'm facing the same issue, but changing the order did not help. this code reproduces the issue:
https://gist.github.com/h3isenbug/74918609f4541a4b392775b729bfd75f

**Comment by ysmood** [comment]
You have the same problem, you should use the HandleAuth before the HijackRequests, but what you are actually doing is using the `go` keyword to run them at the same time.

I think it's a low-level issue that we have to redesign the HandleAuth, I will reopen this issue. We need to merge HandleAuth into HijackRequests, they share the same proto.FetchEnable which will cause the race condition.

**Comment by h3isenbug** [comment]
I'm a little bit confused. Even if i put time.Sleep(time.Second) between two sections(in my code), it does not work 🤷‍♂️

**Comment by ysmood** [comment]
This code will work

```go
go browser.MustHandleAuth(proxyUsername, proxyPassword)()

page.MustNavigate("https://whatever.com")

time.Sleep(3 * time.Second) // wait until the MustHandleAuth finish the auth before we create a router

router := page.HijackRequests()
```

**Comment by h3isenbug** [comment]
thanks, now i got it. can't i set Proxy-Authorization on every request, instead of HandleAuth?

**Comment by ysmood** [comment]
> thanks, now i got it. can't i set Proxy-Authorization on every request, instead of HandleAuth?

I think devtools doesn't support this. You can set up a MITM proxy to do the auth transparently.
