### ISSUE TITLE
panic: fork/exec /tmp/rod/chromium-818858/chrome-linux/chrome: permission denied

### ISSUE THREAD

**Issue by duolaAOA** [go-rod/rod#294]
**Rod Version:** v0.81.3

## The code to demonstrate your question

This is a panic when running on centos7.4, but there is no problem when running on macos-catalina-10.15.4
```bash
[root@rod dc]# /home/rod/dc -c ./config -f ./urls
Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/818858/chrome-linux.zip
Progress: 00% 12% 20% 24% 31% 38% 42% 51% 61% 67% 73% 84% 98% 100%
Downloaded: /tmp/rod/chromium-818858.zip
Unzip to: /tmp/rod/chromium-818858
Progress: 00% 24% 47% 64% 95% 100%

panic: fork/exec /tmp/rod/chromium-818858/chrome-linux/chrome: permission denied

goroutine 1 [running]:
main.setBrowser(0xc000023200)
        /home/rod/dc.go:92 +0x884
main.main()
        /home/roddc.go:150 +0x2d1
```

This is my code from line 81 to line 99
```go
func setBrowser() (browser *rod.Browser) {
	l, err := launcher.New().
		Set("disable-web-security").
		Set("disable-setuid-sandbox").
		Set("no-sandbox").
		Set("no-first-run", "true").
		Set("disable-gpu").
		Set("disable-extensions").
		Headless(config.Conf.GetBool("rod.Headless")).
		Launch()
	if err != nil {
		panic(err)
	}

	browser = rod.New().ControlURL(l).Trace(config.Conf.GetBool("rod.Trace")).MustConnect()
	browser.MustIncognito().MustPage("")

	return
}
```

## What have you tried to solve the question
This problem occurred when I upgraded from 0.51.0 to 0.81.3

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/issues/222#issuecomment-694784409

**Comment by StefMa** [comment]
I have the same issue but running on [vercel.com](https://vercel.com/)
This is the output:
```
Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/818858/chrome-linux.zip
Progress: 00% 92% 100%
Downloaded: /tmp/rod/chromium-818858.zip
Unzip to: /tmp/rod/chromium-818858
Progress: 00% 12% 25% 38% 47% 56% 65% 76% 95% 100%
panic: fork/exec /tmp/rod/chromium-818858/chrome-linux/chrome: permission denied
goroutine 10 [running]:
github.com/go-rod/rod/lib/utils.E(...)
	/tmp/49d46242/pkg/mod/github.com/go-rod/rod@v0.85.6/lib/utils/utils.go:63
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc00018e480, 0xc0000a2058, 0xcb2040)
	/tmp/49d46242/pkg/mod/github.com/go-rod/rod@v0.85.6/lib/launcher/launcher.go:305 +0xcd
github.com/go-rod/rod.(*Browser).Connect(0xc00020e000, 0x0, 0xc000054db0)
	/tmp/49d46242/pkg/mod/github.com/go-rod/rod@v0.85.6/browser.go:144 +0x413
github.com/go-rod/rod.(*Browser).MustConnect(0xc00020e000, 0xc00018ba40)
	/tmp/49d46242/pkg/mod/github.com/go-rod/rod@v0.85.6/must.go:27 +0x2f
```

Installing it manually (what you suggest in your comment) is not really an option.

Any other ideas to fix it?

**Comment by ysmood** [comment]
I don't have any good ideas yet, maybe you can raise an issue for it: Auto handles Linux download like `apt` or `yum`.

If you spend some time to make a PR for your Linux distro, I will be more than glad to merge it.
