### ISSUE TITLE
Race condition when element referenced by Must* panic is removed from browser 

### ISSUE THREAD

**Issue by jackc** [go-rod/rod#319]
**Rod Version:** v0.85.9

## Steps to reproduce

`MustClick` on an element that is not clickable because is is covered by another. The covering element is removed while / before the panic is handled.

In my particular case this occurs after interacting with a modal. The modal has an semi-transparent gray element that covers the entire page and fades away when the modal is dismissed. Immediately use `MustClick` on the underlying page.

The failure only occurs maybe 1 time out of 20.

## Expected behavior

I should see the error message `element covered by: ...` in the panic. 

## Actual result

A panic with the message `fatal error: panic while printing panic value`.

**Comment by ysmood** [comment]
Can you provide minimal code for us to reproduce your issue?

May be duplicated with #244.

**Comment by jackc** [comment]
It's tricky to know if a race condition will duplicate on another machine... but this consistently fails for me.

```go
package main

import (
	"net/http"

	"github.com/go-rod/rod"
)

var html = []byte(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
	<title>Rod Issue 319 Example</title>

	<style>
		#overlay {
			background-color: black;
			z-index: 999;
			opacity: 0.5;
			position: fixed;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}
	</style>
</head>

<body>
	<div id="overlay">Covering element</div>
	<button>Click Me!</button>
</body>
</html>
`)

func main() {
	go func() {
		http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) { w.Write(html) })
		http.ListenAndServe("127.0.0.1:8090", nil)
	}()

	browser := rod.New().MustConnect()
	defer browser.MustClose()
	page := browser.MustPage("http://127.0.0.1:8090/")

	page.MustEval(`setTimeout(function() { document.getElementById("overlay").style.display = "none" }, 500)`)
	page.MustElement("button").MustClick()
}
```

Here's a stack trace:

```
jack@glados ~/dev/rod-319 » go run main.go                                                                                                                                                                
fatal error: panic while printing panic value

goroutine 1 [running]:
runtime.throw(0x1464dab, 0x20)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc0001659c0 sp=0xc000165990 pc=0x1036b12
runtime.preprintpanics.func1()
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:665 +0x56 fp=0xc0001659e8 sp=0xc0001659c0 pc=0x1063556
runtime.call32(0x0, 0x15e4020, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/asm_amd64.s:540 +0x3e fp=0xc000165a18 sp=0xc0001659e8 pc=0x10698de
runtime.reflectcallSave(0xc000165b58, 0x15e4020, 0x0, 0xc000000000)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:881 +0x58 fp=0xc000165a48 sp=0xc000165a18 pc=0x10360f8
runtime.runOpenDeferFrame(0xc000000180, 0xc0000b00f0, 0xc000165ba0)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:855 +0x2cd fp=0xc000165ad8 sp=0xc000165a48 pc=0x1035fad
panic(0x13d2bc0, 0xc0000a1e10)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9 fp=0xc000165ba0 sp=0xc000165ad8 pc=0x1036379
github.com/go-rod/rod/lib/utils.E(...)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/lib/utils/utils.go:63
github.com/go-rod/rod.(*Element).MustHTML(0xc000097dd0, 0xc0000b0138, 0x800000008)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/must.go:758 +0xcd fp=0xc000165c00 sp=0xc000165ba0 pc=0x134982d
github.com/go-rod/rod.(*ErrCovered).Error(0xc0000ac2f8, 0x1453d60, 0xc0000ac2f8)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/error.go:140 +0x32 fp=0xc000165c58 sp=0xc000165c00 pc=0x1347e32
runtime.preprintpanics(0xc000165d38)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:671 +0xa9 fp=0xc000165cb8 sp=0xc000165c58 pc=0x1035909
panic(0x1453d60, 0xc0000ac2f8)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:1062 +0x532 fp=0xc000165d80 sp=0xc000165cb8 pc=0x10366f2
github.com/go-rod/rod/lib/utils.E(...)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/lib/utils/utils.go:63
github.com/go-rod/rod.(*Element).MustClick(0xc000096840, 0x14561b3)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/must.go:652 +0xc5 fp=0xc000165dd0 sp=0xc000165d80 pc=0x1349745
main.main()
	/Users/jack/dev/rod-319/main.go:47 +0x385 fp=0xc000165f88 sp=0xc000165dd0 pc=0x1351bc5
runtime.main()
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/proc.go:204 +0x209 fp=0xc000165fe0 sp=0xc000165f88 pc=0x10392c9
runtime.goexit()
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000165fe8 sp=0xc000165fe0 pc=0x106b2e1

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x9b20858, 0x72, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000a6018, 0x72, 0x0, 0x0, 0x14561a7)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000a6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_unix.go:394 +0x1fc
net.(*netFD).accept(0xc0000a6000, 0xc579a413dc8b0fa9, 0x8d6dc8b0fa9, 0x100000001)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc00009a020, 0x5fe23235, 0xc00005ee08, 0x108a4c6)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00009a020, 0xc00005ee58, 0x18, 0xc000001980, 0x1260a6c)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00009c000, 0x1637fa0, 0xc00009a020, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/http/server.go:2937 +0x266
net/http.(*Server).ListenAndServe(0xc00009c000, 0xc00009c000, 0x1)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/http/server.go:2866 +0xb7
net/http.ListenAndServe(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/http/server.go:3120
main.main.func1()
	/Users/jack/dev/rod-319/main.go:39 +0x96
created by main.main
	/Users/jack/dev/rod-319/main.go:37 +0x5a

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x9b203d0, 0x72, 0x1633780)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000022b18, 0x72, 0x1633700, 0x18027f0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000022b00, 0xc0001e2001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000022b00, 0xc0001e2001, 0x5ff, 0x5ff, 0xc000153d90, 0x104d4cc, 0x600)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000100d0, 0xc0001e2001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/net/net.go:182 +0x8e
encoding/json.(*Decoder).refill(0xc0001349a0, 0xa, 0x9)
	/usr/local/Cellar/go/1.15.6/libexec/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc0001349a0, 0x0, 0x0, 0x1)
	/usr/local/Cellar/go/1.15.6/libexec/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc0001349a0, 0x138f460, 0xc00019cf60, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/encoding/json/stream.go:63 +0x79
github.com/ysmood/leakless.(*Launcher).serve.func1(0x1637fa0, 0xc00000fba0, 0xc00001a940, 0x20, 0xc00000fb00)
	/Users/jack/go/pkg/mod/github.com/ysmood/leakless@v0.6.11/leakless.go:89 +0x2da
created by github.com/ysmood/leakless.(*Launcher).serve
	/Users/jack/go/pkg/mod/github.com/ysmood/leakless@v0.6.11/leakless.go:71 +0xb6

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x9b20688, 0x72, 0x1633780)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0001c43d8, 0x72, 0x1633701, 0x18027f0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c43c0, 0xc0001d6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_unix.go:159 +0x1a5
os.(*File).read(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/file_posix.go:31
os.(*File).Read(0xc0000100a8, 0xc0001d6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/file.go:116 +0x71
io.copyBuffer(0x1632740, 0xc00000fc20, 0x1632b40, 0xc0000100a8, 0xc0001d6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/io/io.go:409 +0x12c
io.Copy(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/io/io.go:368
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:311 +0x65
os/exec.(*Cmd).Start.func1(0xc000134840, 0xc00000fcc0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:441 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:440 +0x629

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x9b204b8, 0x72, 0x1633780)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0001c4498, 0x72, 0x1633701, 0x18027f0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c4480, 0xc0001ce000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/internal/poll/fd_unix.go:159 +0x1a5
os.(*File).read(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/file_posix.go:31
os.(*File).Read(0xc0000100c0, 0xc0001ce000, 0x8000, 0x8000, 0x91, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/file.go:116 +0x71
io.copyBuffer(0x1632740, 0xc00000fc60, 0x1632b40, 0xc0000100c0, 0xc0001ce000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/io/io.go:409 +0x12c
io.Copy(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/io/io.go:368
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:311 +0x65
os/exec.(*Cmd).Start.func1(0xc000134840, 0xc00000fd00)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:441 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:440 +0x629

goroutine 10 [syscall]:
syscall.syscall6(0x107df20, 0x9c86, 0xc00004c6ac, 0x0, 0xc000198090, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/sys_darwin.go:85 +0x2e
syscall.wait4(0x9c86, 0xc00004c6ac, 0x0, 0xc000198090, 0x90, 0x1444740, 0x1)
	/usr/local/Cellar/go/1.15.6/libexec/src/syscall/zsyscall_darwin_amd64.go:44 +0x87
syscall.Wait4(0x9c86, 0xc00004c6fc, 0x0, 0xc000198090, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/syscall/syscall_bsd.go:129 +0x51
os.(*Process).wait(0xc0000202a0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec_unix.go:43 +0x85
os.(*Process).Wait(...)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc000134840, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.6/libexec/src/os/exec/exec.go:507 +0x65
github.com/go-rod/rod/lib/launcher.(*Launcher).Launch.func1(0xc000134840, 0xc000022800)
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/lib/launcher/launcher.go:354 +0x2b
created by github.com/go-rod/rod/lib/launcher.(*Launcher).Launch
	/Users/jack/go/pkg/mod/github.com/go-rod/rod@v0.85.9/lib/launcher/launcher.go:353 +0x209
exit status 2
```

**Comment by ysmood** [comment]
Remove the `defer browser.MustClose()` will fix your problem. The reason is that you don't give the error report enough time to get the error info from the browser.

**Comment by ysmood** [comment]
The v0.86.0 should have fixed it, please check.

**Comment by jackc** [comment]
Yes, that fixed it.

As far as not having a `defer browser.MustClose()`, that will require a bit of gymnastics in my actual use case. I'm using it inside of tests, and fatal test errors are propagated via panic to the test framework. So if my test creates a browser it is difficult to avoid closing the browser before the underlying error is evaluated.
