### ISSUE TITLE
MustClick() and Click() undefined behavior/broken

### ISSUE THREAD

**Issue by GTANAdam** [go-rod/rod#472]
**Rod Version:** v0.101.5

Some weird inconsistent behavior in both MustClick() and Click(), the former crashes and the latter gets stuck waiting for interact to end.

## The code to demonstrate your question

```go
func main() {
    page.MustElement(`div.styles_content__3rHRc`).MustClick()
}
```
```go
func main() {
    page.MustElement(`div.styles_content__3rHRc`).Click(proto.InputMouseButtonLeft)
}
```

MustClick():
```
[rod] 2021/08/14 01:59:19 [query] rod.element("div.styles_content__3rHRc") div.styles_item__2kQQ5 <page:6F91EFE4>
[rod] 2021/08/14 01:59:19 [wait] interactable <div.styles_content__3rHRc>
[rod] 2021/08/14 01:59:19 [input] scroll into view <div.styles_content__3rHRc>
[rod] 2021/08/14 01:59:19 [wait] visible <div.styles_content__3rHRc>
[rod] 2021/08/14 01:59:19 [wait] stable RAF <div.styles_content__3rHRc>
panic: {-32000 Argument should belong to the same JavaScript world as target object }

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func1(0x706380, 0xc000494f30)
        C:/Users/Adam/go/pkg/mod/github.com/go-rod/rod@v0.101.5/lib/utils/utils.go:64 +0x3c
github.com/go-rod/rod.genE.func1(0xc000165160, 0x1, 0x1)
        C:/Users/Adam/go/pkg/mod/github.com/go-rod/rod@v0.101.5/must.go:35 +0x9c
github.com/go-rod/rod.(*Element).MustClick(0xc000494090, 0x7b2e80)
        C:/Users/Adam/go/pkg/mod/github.com/go-rod/rod@v0.101.5/must.go:719 +0xbb
main.main()
        C:/Users/Adam/.../main.go:109 +0xb98
exit status 2
```

## What have you tried to solve the question
Have used Eval instead.

```go
func main() {
    page.MustElement(`div.styles_content__3rHRc`).MustEval(`this.click()`)
}
```

**Comment by ysmood** [comment]
If we read the source code of MustClick, how can they be different?

https://github.com/go-rod/rod/blob/4f045fd526c3f2ec143d5eafbb0b2961d09881b6/must.go#L717

**Comment by GTANAdam** [comment]
> If we read the source code of MustClick, it's just a shortcut, how can they be different?
> 
> https://github.com/go-rod/rod/blob/4f045fd526c3f2ec143d5eafbb0b2961d09881b6/must.go#L717-L721

I haven't seen the source code but that's very odd!

**Comment by ysmood** [comment]
I will close it until we collect more info.
