### ISSUE TITLE
Getting 'panic: context deadline exceeded' when increasing number of instances over 6

### ISSUE THREAD

**Issue by alicazi** [go-rod/rod#484]
**Rod Version:** v0.101.6

I'm getting the following error when increased number of instances. The code works perfectly fine up to 6 concurrent instances but over with 7 or 8 concurrent instances the error start showing up
- I'm using Must with Timeout
- I'm handling timeouts and other panics using recover
- recoverMe() taking screenshots,  handling timeouts, etc.
the following error is not getting caught by recoverMe and crashing the app :

```
panic: context deadline exceeded
goroutine 1459 [running]:
github.com/go-rod/rod/lib/utils.glob..func1({0x158ac00, 0x1c2a6c0})
	/Users/.../go/src/pkg/mod/github.com/go-rod/rod@v0.101.5/lib/utils/utils.go:64 +0x25
github.com/go-rod/rod.genE.func1({0xc0003a4970, 0x1, 0x1})
	/Users/.../go/src/pkg/mod/github.com/go-rod/rod@v0.101.5/must.go:35 +0x106
github.com/go-rod/rod.(*Page).MustElementX(0xc0005900a0, {0xc000224ba0, 0x5d})
	/Users/../go/src/pkg/mod/github.com/go-rod/rod@v0.101.5/must.go:534 +0x150
...
```

```
// Recover from panic or rod timeout and report
func recoverMe(b *g.BrowserStatus, tcName string) {
	var val interface{}
	if val = recover(); val != nil {
		var ok bool
		err, ok := val.(error)
		if !ok {
			err = &rod.ErrTry{Value: val}
		}
		handleError(b, err, tcName)
		// Close the browser in case of error
		startup.CloseBrowser(b)
	}
}

var scrShotNum int = 0

func handleError(b *g.BrowserStatus, err error, tcName string) {
	var evalErr *rod.ErrEval
	p := b.Page
	scrShotNum++
	num := fmt.Sprintf("%03d", scrShotNum)
	scrShotName := "_" + num + tcName + ".jpeg"
	report.Console("Info", "See screenshot: "+scrShotName)
	p.MustScreenshot(scrShotName)
	(*g.Tests)[tcName].ScrShotNum++
	if errors.Is(err, context.DeadlineExceeded) { // timeout error
		report.ExpectTimeout()
	} else if errors.As(err, &evalErr) { // eval error
		fmt.Println(evalErr)
		errStr := fmt.Sprintf("%v", err)
		report.ExpectPanic(errStr)
	} else if err != nil { // Unknown error
		errStr := fmt.Sprintf("%v", err)
		report.ExpectUnknown(errStr)
	}

}
```
I searched go-rod source to find any variable or const related to any deadline that I can change but no success so far.
Please let me know if there is a way to increase the deadline or handling  this error to stop crashing the code.

**Comment by alicazi** [comment]
I found the issue. It was missing recoverMe() in a startup function.
