### ISSUE TITLE
When i import gorod and gopsutil it will shows me panic error 当我导入gorod和gopsutil的时候 使用gopsutil去结束chromium进程 出现 panic: [launcher] Failed to get the debug url: 错误

### ISSUE THREAD

**Issue by tpsmr** [go-rod/rod#545]
**Rod Version:** latest

## The code to demonstrate your question

```
package main

import (
	"os"
	"time"
	"strings"
	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/shirou/gopsutil/process"
)

func main() {
	u := launcher.New().
	UserDataDir("path").
	Headless(false).
	MustLaunch()
	browser := rod.New().ControlURL(u).MustConnect()
	page := browser.MustPage("https://www.earthol.com/")
	//document.querySelector('[name="x"]')
	//document.querySelectorAll('[name="y"]')
	page.MustElement(`[name="x"]`).MustInput("1")
	page.MustElement(`[name="y"]`).MustInput("1")
	page.MustElement(`[value="前往"]`).MustClick()
	//page.Close()
	time.Sleep(10 * time.Second)
	//page.Close()
	//KillChrome()
}

func KillChrome() {
	softs, _ := process.Processes()
	for _, soft := range softs {
		cl, _ := soft.CmdString()
		if strings.Contains(cl, "c") {
			KillChildren(soft)
			soft.Terminate()
			soft.Kill()
			time.Sleep(1 * time.Second)
		}
	}
}

func KillChildren(p *process.Process) {
	children, _ := p.Children()
	for _, child := range children {
		child.Terminate()
		child.Kill()
	}
}
```

this line shows bug 这行报错
```
u := launcher.New().
	UserDataDir("path").
	Headless(false).
	MustLaunch()
```

error:
```
go run main.go
panic: [launcher] Failed to get the debug url: �������е��������Ự�д򿪡�


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2(0x92f160, 0x118069e0)
        C:/Program Files/go/gopath/src/github.com/go-rod/rod/lib/utils/utils.go:57 +0x29
github.com/go-rod/rod/lib/utils.E(...)
        C:/Program Files/go/gopath/src/github.com/go-rod/rod/lib/utils/utils.go:63
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0x1183b800, 0x9ae900, 0x1183b800)
        C:/Program Files/go/gopath/src/github.com/go-rod/rod/lib/launcher/launcher.go:335 +0xa1
main.main()
        C:/Program Files/go/gopath/src/ge/main.go:16 +0x52
exit status 2
```

**Comment by tpsmr** [comment]
when i use page.close.it shows same error

**Comment by ysmood** [comment]
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/1415488/155319934-4bdd56ba-e2de-47fa-a7d2-e3b7ca40821b.png">
