### ISSUE TITLE
net::ERR_CONNECTION_CLOSED net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by breezemight** [go-rod/rod#580]
**Rod Version:** v0.105.1

Screenshotting urls with bad ssl certificate fails and raises error.

The code I wrote :

```golang

func main() {
        path := "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
        u := launcher.New().Bin(path).MustLaunch()

        screenshot("https://urlwithbadssl.com", u)
}

func screenshot(uri, u string) {

	buf, err := rod.New().ControlURL(u).MustConnect().MustPage(uri).
		MustWaitLoad().Screenshot(true, &proto.PageCaptureScreenshot{
		Format:  proto.PageCaptureScreenshotFormatJpeg,
		Quality: gson.Int(90),
	})

	if err != nil {
		log.Fatal(uri, ":", err)
	}

	err = ioutil.WriteFile(<path code here>, buf, 0644)
	if err != nil {
		log.Fatal(err)
	}
}

```

Error raised by it :

```golang
panic: navigation failed: net::ERR_CONNECTION_CLOSED

goroutine 160 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x6558a0?, 0xc00038ce50?})
	C:/Users/User/go/pkg/mod/github.com/go-rod/rod@v0.105.1/lib/utils/utils.go:57 +0x25
github.com/go-rod/rod.genE.func1({0xc00040d250?, 0x17?, 0x0?})
	C:/Users/User/go/pkg/mod/github.com/go-rod/rod@v0.105.1/must.go:35 +0x5a
github.com/go-rod/rod.(*Browser).MustPage(0xc00029a700, {0xc0005edef8?, 0x0?, 0x0?})
	C:/Users/User/go/pkg/mod/github.com/go-rod/rod@v0.105.1/must.go:70 +0xd3
main.screenshot({0x6f1ccf, 0x17}, {0xc0000c8000, 0x49}) ...
```

How can I make rod ignore the SSL certificate check?

**Comment by ysmood** [comment]
#322

**Comment by breezemight** [comment]
thanks

**Comment by breezemight** [comment]
@go-rog/everyone

**Comment by ysmood** [comment]
`Browser.IgnoreCertErrors`

**Comment by breezemight** [comment]
I changed the first block of main function with this :
```golang 
buf, err := rod.New().ControlURL(u).MustConnect().Timeout(30 * time.Second).MustIgnoreCertErrors(true).MustPage(uri).
	MustWaitLoad().Screenshot(true, &proto.PageCaptureScreenshot{
	Format:  proto.PageCaptureScreenshotFormatJpeg,
	Quality: gson.Int(90),
})
``` 

now most of the urls with bad ssl are being screenshot. But a new error appeared :
```
 panic: navigation failed: net::ERR_CONNECTION_CLOSED
```

**Comment by ysmood** [comment]
https://go-rod.github.io/#/error-handling

**Comment by breezemight** [comment]
I'm already catching the error above but these errors will directly panic instead, making the `err` variable above completely useless. Totally not a design flaw or anything.
here's another brand new error : 
```
panic: context deadline exceeded
```
I'm so done.

**Comment by ysmood** [comment]
why not use the `rod.Try`?
