### ISSUE TITLE
Does launcher support linux arm64?

### ISSUE THREAD

**Issue by knowlet** [go-rod/rod#586]
**Rod Version:** v0.106.0

## The code to demonstrate your question

```go
package main

import "github.com/go-rod/rod"

func main() {
	page := rod.New().MustConnect().MustPage("https://www.wikipedia.org/")
	page.MustWaitLoad().MustScreenshot("a.png")
}
```

See error:
```
$ go run main.go 
Download: https://storage.googleapis.com/chromium-browser-snapshots//991974/
panic: failed to download the browser: 404 <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots//991974/</Details></Error>

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x3565e0?, 0x40000a0f20?})
        /home/ubuntu/go/pkg/mod/github.com/go-rod/rod@v0.106.0/lib/utils/utils.go:59 +0x28
github.com/go-rod/rod.genE.func1({0x40000ee400?, 0x0?, 0x0?})
        /home/ubuntu/go/pkg/mod/github.com/go-rod/rod@v0.106.0/must.go:35 +0x68
github.com/go-rod/rod.(*Browser).MustConnect(0x40001619e0)
        /home/ubuntu/go/pkg/mod/github.com/go-rod/rod@v0.106.0/must.go:50 +0x90
main.main()
        /home/ubuntu/rod-test/main.go:6 +0x24
exit status 2
```

## What have you tried to solve the question

It seems the Download browser function does not list linux arm64 in the map?
https://github.com/go-rod/rod/blob/e0d0a7eea5010ba6786e2cd6000fa09eab926704/lib/launcher/browser.go#L26-L35

It seems that Google does not have a prebuilt binary for linux arm, so we should either compile our own and host one according to [the recipes](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/linux/chromium_arm.md), or we can use the prebuilt binary by adding a [Playwright](https://github.com/microsoft/playwright) host?

**Comment by ysmood** [comment]
Good idea, may I ask you where did you find out the `"https://playwright.azureedge.net/builds/%s/%d/%s"`

**Comment by knowlet** [comment]
The url is in [build.sh](https://github.com/microsoft/playwright/blob/main/browser_patches/checkout_build_archive_upload.sh#L451) and the revision and file name is in folder [browser_patches/chromium](https://github.com/microsoft/playwright/tree/main/browser_patches/chromium) `EXPECTED_BUILDS` and 
 `BUILD_NUMBER` file.

**Comment by ysmood** [comment]
Is there a way to get the latest revision automatically from the playwright repo?

**Comment by knowlet** [comment]
@ysmood It seems it will update latest revision after their builds in the [`BUILD_NUMBER`](https://github.com/microsoft/playwright/blob/main/browser_patches/chromium/BUILD_NUMBER) file.

**Comment by ysmood** [comment]
The file content is `1003` which is not `983172`, I think we need a way to map `1003` to `983172`, do you know how to do that?

**Comment by ysmood** [comment]
https://github.com/go-rod/rod/releases/tag/v0.106.3
