### ISSUE TITLE
Alert crashes

### ISSUE THREAD

**Issue by aadog** [go-rod/rod#599]
**Rod Version:** v0.0.0

github.com/go-rod/rod v0.106.6-0.20220507105211-27a23eccf51a // indirect

## The code to demonstrate your question

```go
func main() {
	p, _ := launcher.LookPath()
	u := launcher.New().Bin(p).Headless(false).MustLaunch()
	page := rod.New().ControlURL(u).MustConnect().MustPage("https://www.baidu.com")
	page.MustWaitLoad().MustEval(`alert('ok')`)

	time.Sleep(time.Second * 5)
}
```

## What have you tried to solve the question

```
panic: eval js error: TypeError: Cannot read properties of undefined (reading 'apply')
    at <anonymous>:1:36 <nil>

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xed07c0, 0xc00039c068})
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/lib/utils/utils.go:59 +0x25
github.com/go-rod/rod.genE.func1({0xc0003921b0, 0x1, 0x1})
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/must.go:35 +0x106
github.com/go-rod/rod.(*Page).MustEval(0xc00008e160, {0xf66b8b, 0xb}, {0x0, 0x0, 0x0})
        C:/Users/pwt/go/pkg/mod/github.com/go-rod/rod@v0.106.6-0.20220507105211-27a23eccf51a/must.go:426 +0x190
main.main()
        C:/Users/pwt/src/awesomeProject/main.go:13 +0x156

```

**Comment by ysmood** [comment]
Please read the doc of `Page.Eval`
