### ISSUE TITLE
Panic when i try to get element form iframe

### ISSUE THREAD

**Issue by ITChelik** [go-rod/rod#628]
### **Rod Version:** v0.107.2

```go
package main

import (
        "fmt"
   	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main(){
	u := launcher.New().Delete("--headless").MustLaunch()
	page := rod.New().ControlURL(u).MustConnect().MustPage("https://7v1ey6.csb.app/")

	codeFrameInput, err := page.Element("iframe")
	if err != nil {
		fmt.Println(err)
		return
	}
	framed, err := codeFrameInput.Frame()
	if err != nil {
		fmt.Println(err)
		return
	}
	codeInput, err := framed.Element(".tui-input__input") // panic
	if err != nil {
		fmt.Println(err)
		return
	}
	err = codeInput.Input("1234")
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

## What you got
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x168d04b]

goroutine 1 [running]:
github.com/go-rod/rod.(*Page).getJSCtxID(0xc0002460b0)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/page_eval.go:349 +0x12b
github.com/go-rod/rod.(*Page).ensureJSHelper(0x2?, 0x2c52f80)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/page_eval.go:248 +0x3e
github.com/go-rod/rod.(*Page).formatArgs(0x1b97d8c?, 0x244a530?)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/page_eval.go:233 +0x235
github.com/go-rod/rod.(*Page).evaluate(0x2f27108?, 0xc000100cc0)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/page_eval.go:149 +0x3b
github.com/go-rod/rod.(*Page).Evaluate(0xc0002460b0, 0xc000100cc0)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/page_eval.go:128 +0x4e
github.com/go-rod/rod.(*Page).ElementByJS.func2()
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/query.go:172 +0x97
github.com/go-rod/rod/lib/utils.Retry({0x24427a0, 0xc00065c0c0}, 0xc00067dd70, 0xc00069fb50)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/lib/utils/sleeper.go:142 +0x37
github.com/go-rod/rod.(*Page).ElementByJS(0xc0002460b0, 0xc000100cc0)
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/query.go:167 +0xc5
github.com/go-rod/rod.(*Page).Element(0xc00067d8c0?, {0x1e40a98?, 0x1e390a7?})
Go/pkg/mod/github.com/go-rod/rod@v0.107.2/query.go:143 +0x13b
main.main()
cmd/main.go:41 +0x246
```
## What you expected to see

I want to emulate type `1234` to input element in iframe

## What have you tried to solve the question

Im find `nil pointer dereference` problem, wich contains in `page_eval.go` file, line 349. 
In my case, field `ContentDocument` in `node` object is `nil`.

**Comment by ysmood** [comment]
Duplicated #548
