### ISSUE TITLE
Issues running Firefox

### ISSUE THREAD

**Issue by NuLL3rr0r** [go-rod/rod#635]
**Rod Version:** v0.107.2

## The code to demonstrate your question

1. Clone Rod to your local and cd to the repository:

   ```bash
   git clone https://github.com/go-rod/rod
   cd rod
   ```

1. Use your code to replace the content of function `TestLab` in file `lab_test.go`.

1. Test your code with: `go test -run TestLab`, make sure it fails as expected.

1. Replace the content under "The code to demonstrate your question" with the entire `lab_test.go` content, like below:

```go
package rod_test

import (
	"fmt"
	"testing"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/devices"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
	"github.com/go-rod/stealth"
)

// This is the template to demonstrate how to test Rod.
func TestLab(t *testing.T) {
	//extPath, _ := filepath.Abs("/home/mamadou/dev/bot/tw/extensions/clearcache@michel.de.almeida.xpi")

	u := launcher.NewUserMode().
		Bin("/usr/bin/firefox").
		//Set("-migration").
		UserDataDir("/home/mamadou/dev/bot/tw2").
		ProfileDir("/home/mamadou/dev/bot/tw2").
		Set("-profile /home/mamadou/dev/bot/tw2").
		WorkingDir("").
		StartURL("https://twitter.com").
		Env("DISPLAY=:0").
		Env("LC_ALL=he_IL.UTF-8"). // using Env causes crash
		Env("TZ=Asia/Jerusalem").
		//Set("load-extension", extPath).
		Headless(false)

	userDataDir := u.Get("user-data-dir")
	fmt.Println(userDataDir)

	browser := rod.New().ControlURL(u.MustLaunch()).MustConnect().NoDefaultDevice()

	page := stealth.MustPage(browser)
	page.MustEmulate(devices.Device{
		Title: "Custom Linux Desktop",
		//Capabilities:   []string{"touch", "mobile"},
		UserAgent:      "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0)",
		AcceptLanguage: "en",
		/*Screen: devices.Screen{
			DevicePixelRatio: 2,
			Horizontal: devices.ScreenSize{
				Width:  480,
				Height: 320,
			},
			Vertical: devices.ScreenSize{
				Width:  320,
				Height: 480,
			},
		},*/
	})
	page.MustNavigate("https://amiunique.org/fp")

	defer browser.MustClose()

	utils.Pause()
}

```

## What you got

```
parallel test 16
/home/mamadou/dev/bot/tw2
--- FAIL: TestLab (1.02s)
panic: [launcher] Failed to get the debug url: Error: no DISPLAY environment variable specified
 [recovered]
	panic: [launcher] Failed to get the debug url: Error: no DISPLAY environment variable specified


goroutine 8 [running]:
testing.tRunner.func1.2({0x83e380, 0xc000322000})
	/usr/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x83e380, 0xc000322000})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/go-rod/rod/lib/utils.glob..func2({0x83e380?, 0xc000322000?})
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:59 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:65
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc3a540?)
	/home/mamadou/dev/bot/rod-src/lib/launcher/launcher.go:343 +0x67
github.com/go-rod/rod_test.TestLab(0x0?)
	/home/mamadou/dev/bot/rod-src/lab_test.go:35 +0x50f
testing.tRunner(0xc0000bdd40, 0xaa3f20)
	/usr/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	github.com/go-rod/rod	1.083s
```

## What you expected to see

1, Run Firefox and load my desired profile, None of the following works:

```go
UserDataDir("/home/mamadou/dev/bot/tw2").
ProfileDir("/home/mamadou/dev/bot/tw2").
Set("-profile /home/mamadou/dev/bot/tw2").
```

2. Setting ENV vars such as LC_ALL and TZ. Commenting the following lines everything works. I tried ```echo $DISPLAY``` and use that from Go as seen in the example and it won't work.

```go
//Env("LC_ALL=he_IL.UTF-8"). // using Env causes crash
//Env("TZ=Asia/Jerusalem").
```

## What have you tried to solve the question

I was not able to figure this out, hence I am asking here.

**Comment by NuLL3rr0r** [comment]
I've just noticed this is not a Firefox-only issue, it seems setting the Env crashes chrome as well:

```
panic: [launcher] Failed to get the debug url: [12037:12037:0626/014712.802964:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[12037:12037:0626/014712.802985:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
```

**Comment by NuLL3rr0r** [comment]
BTW, I am running i3wm if that makes a difference. Chromedp and Playwright-go run just fine.

**Comment by ysmood** [comment]
Your error says:

> Failed to get the debug url: Error: no DISPLAY environment variable specified

Seems like a config issue

**Comment by NuLL3rr0r** [comment]
> Can you show us your test code for chromedp?

Well, it's not test code. It's a whole in production project. But, I took this example from chromedp and added the env vars:

```go
// Command click is a chromedp example demonstrating how to use a selector to
// click on an element.
package main

import (
	"context"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("disable-gpu", false),
		chromedp.Flag("headless", true),
		chromedp.Flag("no-default-browser-check", true),
		chromedp.Flag("no-first-run", true),
		chromedp.Env("LC_ALL=he_IL.UTF-8"),
		chromedp.Env("TZ=Asia/Jerusalem"),
	)

	allocCtx, _ := chromedp.NewExecAllocator(context.Background(), opts...)

	// create chrome instance
	ctx, cancel := chromedp.NewContext(
		allocCtx,
		// chromedp.WithDebugf(log.Printf),
	)
	defer cancel()

	// create a timeout
	ctx, cancel = context.WithTimeout(ctx, 15*time.Second)
	defer cancel()

	// navigate to a page, wait for an element, click
	var example string
	err := chromedp.Run(ctx,
		chromedp.Navigate(`https://pkg.go.dev/time`),
		// wait for footer element is visible (ie, page is loaded)
		chromedp.WaitVisible(`body > footer`),
		// find and click "Example" link
		chromedp.Click(`#example-After`, chromedp.NodeVisible),
		// retrieve the text of the textarea
		chromedp.Value(`#example-After textarea`, &example),
	)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Go's time.After example:\n%s", example)
}
```

It works and outputs (headless or otherwise):
```
2022/06/26 16:46:25 Go's time.After example:
package main

import (
	"fmt"
	"time"
)

var c chan int

func handle(int) {}

func main() {
	select {
	case m := <-c:
		handle(m)
	case <-time.After(10 * time.Second):
		fmt.Println("timed out")
	}
}
```

**Comment by ysmood** [comment]
Have you checked how to use the `Launcher.Set` api:

https://github.com/go-rod/rod/blob/9aab67b659ecdf50d17152ca0eb7a547c5f4aa1c/examples_test.go#L573-L575

Your chromedp example doesn't show any code related to firefox, are you sure chromedp is using firefox?

**Comment by NuLL3rr0r** [comment]
> I've just noticed this is not a Firefox-only issue, it seems setting the Env crashes chrome as well:
> 
> ```
> panic: [launcher] Failed to get the debug url: [12037:12037:0626/014712.802964:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
> [12037:12037:0626/014712.802985:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
> ```

As I mentioned it even won't work with Chromium on my Gentoo installation. I am not sure if chromedp is working with Firefox.

The issue is when I use Env variable to set TZ, LC_ALL, or anything in both Firefox and Chrome, the Go application using rod crashes.

**Comment by NuLL3rr0r** [comment]
Though the first issue (loading a profile) is with Firefox.

**Comment by ysmood** [comment]
> As I mentioned it even won't work with Chromium on my Gentoo installation. I am not sure if chromedp is working with Firefox.

Could you open another issue for it? It's not related to the title. It will confuse people if they search the firefox keywords.

**Comment by NuLL3rr0r** [comment]
Done!

**Comment by ysmood** [comment]
#193
