### ISSUE TITLE
Setting Env variable results in panic

### ISSUE THREAD

**Issue by NuLL3rr0r** [go-rod/rod#638]
**Rod Version:** v0.107.2

## The code to demonstrate your question

```go
package rod_test

import (
	"fmt"
	"testing"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/devices"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
	"github.com/go-rod/stealth"
)

// This is the template to demonstrate how to test Rod.
func TestLab(t *testing.T) {
	//Minimum sample to reproduce

	u := launcher.New().
		StartURL("https://twitter.com").
		Env("LC_ALL=he_IL.UTF-8"). // using Env causes crash
		Env("TZ=Asia/Jerusalem").
		Headless(false)

	userDataDir := u.Get("user-data-dir")
	fmt.Println(userDataDir)

	browser := rod.New().ControlURL(u.MustLaunch()).MustConnect().NoDefaultDevice()

	page := stealth.MustPage(browser)
	page.MustEmulate(devices.Device{
		Title: "Custom Linux Desktop",
		//Capabilities:   []string{"touch", "mobile"},
		UserAgent:      "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0)",
		AcceptLanguage: "en",
		/*Screen: devices.Screen{
			DevicePixelRatio: 2,
			Horizontal: devices.ScreenSize{
				Width:  480,
				Height: 320,
			},
			Vertical: devices.ScreenSize{
				Width:  320,
				Height: 480,
			},
		},*/
	})
	page.MustNavigate("https://amiunique.org/fp")

	defer browser.MustClose()

	utils.Pause()
}
```

## What you got

```txt
 $ go test -run TestLab
parallel test 16
/tmp/rod/user-data/28011a4101cf2e2f
--- FAIL: TestLab (2.61s)
panic: [launcher] Failed to get the debug url: [10296:10296:0627/072057.833734:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[10296:10296:0627/072057.833922:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
 [recovered]
	panic: [launcher] Failed to get the debug url: [10296:10296:0627/072057.833734:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[10296:10296:0627/072057.833922:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.


goroutine 8 [running]:
testing.tRunner.func1.2({0x83d380, 0xc0002ac5c0})
	/usr/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x83d380, 0xc0002ac5c0})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/go-rod/rod/lib/utils.glob..func2({0x83d380?, 0xc0002ac5c0?})
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:59 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:65
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc392a0?)
	/home/mamadou/dev/bot/rod-src/lib/launcher/launcher.go:343 +0x67
github.com/go-rod/rod_test.TestLab(0x0?)
	/home/mamadou/dev/bot/rod-src/lab_test.go:27 +0x2af
testing.tRunner(0xc0000bdba0, 0xaa2ea0)
	/usr/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	github.com/go-rod/rod	2.662s
```

## What you expected to see

The sample code works normally, which doesn't.

## What have you tried to solve the question

We have already discussed this in #635.

**Comment by ysmood** [comment]
Just tested your code on my mac, it works fine.

**Comment by NuLL3rr0r** [comment]
Well, made no difference. If it makes any difference, I am running i3wm and both chromedp and Playwright-go work.

```
❯ cat lab_test.go 
package rod_test

import (
	"testing"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

// This is the template to demonstrate how to test Rod.
func TestLab(t *testing.T) {
	//extPath, _ := filepath.Abs("/home/mamadou/dev/bot/tw/extensions/clearcache@michel.de.almeida.xpi")

	u := launcher.New().
		StartURL("https://twitter.com").
		Env("LC_ALL=he_IL.UTF-8"). // using Env causes crash
		Env("TZ=Asia/Jerusalem").
		Headless(false)

	browser := rod.New().ControlURL(u.MustLaunch()).MustConnect().NoDefaultDevice()
	defer browser.MustClose()

	browser.MustPage("https://amiunique.org/fp")

	utils.Pause()
}

~/dev/bot/rod-src master* ⇣
❯ go test -run TestLab
parallel test 16
--- FAIL: TestLab (1.32s)
panic: [launcher] Failed to get the debug url: [5145:5145:0627/095201.929912:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[5145:5145:0627/095201.929937:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
 [recovered]
	panic: [launcher] Failed to get the debug url: [5145:5145:0627/095201.929912:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[5145:5145:0627/095201.929937:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.


goroutine 19 [running]:
testing.tRunner.func1.2({0x83d380, 0xc00007d940})
	/usr/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x83d380, 0xc00007d940})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/go-rod/rod/lib/utils.glob..func2({0x83d380?, 0xc00007d940?})
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:59 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/mamadou/dev/bot/rod-src/lib/utils/utils.go:65
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc0002536c0?)
	/home/mamadou/dev/bot/rod-src/lib/launcher/launcher.go:343 +0x67
github.com/go-rod/rod_test.TestLab(0x0?)
	/home/mamadou/dev/bot/rod-src/lab_test.go:21 +0x225
testing.tRunner(0xc000238680, 0xa7a568)
	/usr/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	github.com/go-rod/rod	1.374s
```

**Comment by ysmood** [comment]
Change your code to `Env("LC_ALL=he_IL.UTF-8", "TZ=Asia/Jerusalem")`

**Comment by NuLL3rr0r** [comment]
Thank you! This seem to work:

```
package rod_test

import (
	"os"
	"testing"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

// this is the template to demonstrate how to test rod.
func testlab(t *testing.t) {
	u := launcher.new().
		starturl("https://twitter.com").
		env(append(os.environ(), "lc_all=he_il.utf-8", "tz=asia/jerusalem")...).
		//env("lc_all=he_il.utf-8"). // using env causes crash
		//	env("tz=asia/jerusalem").
		headless(false)

	browser := rod.new().controlurl(u.mustlaunch()).mustconnect().nodefaultdevice()
	defer browser.mustclose()

	browser.mustpage("https://amiunique.org/fp")

	utils.pause()
}
```
