### ISSUE TITLE
Support linux arm

### ISSUE THREAD

**Issue by cnmade** [go-rod/rod#673]
```

panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /root/.cache/rod/browser/chromium-1030087/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x34a4c0?, 0x4000448290?})
        /root/go/pkg/mod/github.com/go-rod/rod@v0.108.2/lib/utils/utils.go:59 +0x28
github.com/go-rod/rod.genE.func1({0x40004482a0?, 0x0?, 0x0?})
        /root/go/pkg/mod/github.com/go-rod/rod@v0.108.2/must.go:36 +0x68
github.com/go-rod/rod.(*Browser).MustConnect(0x400011a360)
        /root/go/pkg/mod/github.com/go-rod/rod@v0.108.2/must.go:51 +0x90
main.main()
        /root/workspace/jin10/main.go:10 +0x24
exit status 2
```

**Comment by cnmade** [comment]
After install libnss3, it still got problem

```
panic: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /root/.cache/rod/browser/chromium-1030087/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

```

**Comment by cnmade** [comment]
I think the document should describe to install the depends on linux , i am using Ubuntu linux 21.10 ARM 64

**Comment by ysmood** [comment]
I think rod should just work if you use the default config, I should download the binary automatically:

```go
https://github.com/go-rod/rod/blob/4710d7f82e7892a0699a5cd124d63e55459ad2ae/lib/launcher/browser.go#L59-L69
```
