### ISSUE TITLE
got erron when download file

### ISSUE THREAD

**Issue by bsbak** [go-rod/rod#71]
file length is about 11 mb
```
panic: write tcp 127.0.0.1:58879->127.0.0.1:58877: use of closed network connection

goroutine 1 [running]:
github.com/ysmood/kit/pkg/utils.E(0xc00024c0f0, 0x1, 0x1, 0x0, 0xe20408, 0x1a)
        C:/workspace/go/src/github.com/ysmood/kit/pkg/utils/utils.go:33 +0xb2
github.com/ysmood/rod.(*Page).Element(0xc0000ee240, 0xe20408, 0x1a, 0xc00042c160)
        C:/workspace/go/src/github.com/ysmood/rod/sugar.go:316 +0x101
main.main()
        C:/workspace/go/src/github.com/bsbak/rodtest/main.go:47 +0x703
```

code:

```go
package main

import (
	"log"
	"time"

	"github.com/ysmood/kit"
	"github.com/ysmood/rod"
	"github.com/ysmood/rod/lib/launcher"
)

func main() {
	l := launcher.New().
		// Set("proxy-server", "socks5://62.109.6.251:8000").
		Delete("use-mock-keychain").
		Set("no-sandbox", "true").
		Set("disable-web-security", "true").
		Delete("enable-automation").
		Headless(false).
		Launch()

	browser := rod.New().Trace(true).Slowmotion(200 * time.Millisecond).ControlURL(l).Connect()
	defer browser.Close()
	//login input
	page := browser.Page("https://ekrs.ms.gov.pl/rdf/pd/search_df").WindowMaximize()
	page.Element("[id='unloggedForm:krs2']").Input("0000368923")
	//login submit
	wait := page.WaitRequestIdle()
	page.Element("[id='unloggedForm:submit']").Click()
	wait()

	page.Mouse.Scroll(0, 400)
	//link 1 click - open modal
	wait_click := page.WaitRequestIdle()
	page.Element(`[id='searchForm:docTable:3:j_idt192']`).Click()
	wait_click()
	//download link - download file
	download_wait := page.GetDownloadFile("https://ekrs.ms.gov.pl/rdf/pd/*")
	// page.Element(`[id="searchForm:j_idt292"]`).WaitStable().Click() // this not work
	el := page.Element(`[id="searchForm:j_idt292"]`).WaitStable() // this work
	el.Eval(`() => { this.click(); }`)                            // this work

	content := download_wait()
	log.Println(content[1:11])
	// // close modal
	// close_request := page.WaitRequestIdle()
	page.Element(`[id="searchForm:j_idt201"]`).Click().WaitVisible()
	// close_request()

	// //link 2 click - open modal
	// wait_click2 := page.WaitRequestIdle()
	// page.Element(`[id='searchForm:docTable_data'] .ui-commandlink.ui-widget:nth-child(2)`).Click()
	// wait_click2()

	kit.Pause()

}

```

**Comment by ysmood** [comment]
Is this one duplicated with #69?

**Comment by bsbak** [comment]
yes! if file length around 2 mb its works fine! but if its 11 mb it fails, im just trying to understand why?

**Comment by ysmood** [comment]
Can you help to create a server and simulate large file downloading? The recommended lib to simulate the server is https://github.com/gin-gonic/gin, you can also use others.

**Comment by ysmood** [comment]
In Japan, it takes me forever to open your website, if you ask me to download 11mb file it the progress bar says 1hours 😂 . It's really hard for me to debug your problem. Can you provide an example that doesn't depend on this website?

**Comment by bsbak** [comment]
I was enable proxy on vps server (u can use ur if if you have)! Just uncomment proxy line! Above, I wrote an example where a file is downloaded that leads to an error ... for you, you only need to copy the code and run ... and you will see the same error as I, can please explain me why It cant download the long file?

**Comment by ysmood** [comment]
Sorry, still too slow to debug.

**Comment by ysmood** [comment]
I think 8e24bf35ca823b650bea1f5fc4e242ad155e01ce has fixed your issue. `v0.42.0`
