### ISSUE TITLE
How to use user data dir in Docker mode[v0.107.1]?

### ISSUE THREAD

**Issue by 8treenet** [go-rod/rod#752]
### How to use user data dir in Docker mode?

```sh
docker run -p 7317:7317 ghcr.io/go-rod/rod
```

```go
func TestDockerUserData(t *testing.T) {
	l := launcher.MustNewManaged("").Set("user-data-dir", "/tmp/testuser") //ws://127.0.0.1:7317

	browser := rod.New().Client(l.MustClient()).MustConnect()
	defer browser.MustClose()
	page := stealth.MustPage(browser)
	page.MustNavigate("https://google.com")
	return
}
```

```sh
panic: websocket bad handshake: 400 Bad Request. not allowed user-data-dir path: /tmp/testuser [recovered]
	panic: websocket bad handshake: 400 Bad Request. not allowed user-data-dir path: /tmp/testuser

goroutine 7 [running]:
testing.tRunner.func1.2({0xcfbf40, 0xc00007d880})
	/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0xcfbf40, 0xc00007d880})
```

**Comment by 8treenet** [comment]
v0.107.1

**Comment by ysmood** [comment]
Currently, you can only use dir under `/tmp/rod/user-data/` like `/tmp/rod/user-data/my-dir`,
you can read the source code to check how it works:

https://github.com/go-rod/rod/blob/17b8fba7c0a32493491528b15d9749d83a128bb3/lib/launcher/manager.go#L126

**Comment by ysmood** [comment]
If you want to disable the protection, use the `-allow-all` flag:

```bash
docker run -p 7317:7317 ghcr.io/go-rod/rod:arm-dev rod-manager -allow-all
```
