### ISSUE TITLE
Running example of remotely managed Launcher is not working

### ISSUE THREAD

**Issue by vitorarins** [go-rod/rod#769]
I started to work with go-rod today because it looks like a great project. First thing I tried was the [launch-managed example](https://github.com/go-rod/rod/blob/master/lib/examples/launch-managed/main.go).

Unfortunately it didn't work with latest version of the go-rod image.
This is the (relevant) output from the container:

```
:~$ docker run -it --rm -p 7317:7317 ghcr.io/go-rod/rod:v0.112.1
[rod-manager] listening on: [::]:7317
[launcher.Browser]2022/11/29 14:25:10 try to find the fastest host to download the browser binary
[launcher.Browser]2022/11/29 14:25:10 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1065323/chrome-linux.zip
[launcher.Browser]2022/11/29 14:25:10 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1065323/chrome-linux.zip
[launcher.Browser]2022/11/29 14:25:10 check https://playwright.azureedge.net/builds/chromium/1065323/chromium-linux-arm64.zip
[launcher.Browser]2022/11/29 14:25:11 check result: Get "https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1065323/chrome-linux.zip": context canceled
[launcher.Browser]2022/11/29 14:25:11 check result: Get "https://playwright.azureedge.net/builds/chromium/1065323/chromium-linux-arm64.zip": context canceled
[launcher.Browser]2022/11/29 14:25:11 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1065323/chrome-linux.zip
[launcher.Browser]2022/11/29 14:25:11 Progress:
[launcher.Browser]2022/11/29 14:25:11 00%
...
[launcher.Browser]2022/11/29 14:25:48 100%
[launcher.Browser]2022/11/29 14:25:48 Unzip to: /root/.cache/rod/browser/chromium-1065323
[launcher.Browser]2022/11/29 14:25:48 Progress:
[launcher.Browser]2022/11/29 14:25:48 00%
...
[launcher.Browser]2022/11/29 14:25:51 100%
2022/11/29 14:25:53 http: panic serving 172.17.0.1:40210: [launcher] Failed to get the debug url: 
goroutine 8 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x6eb4c0, 0xc0000d4080})
	/usr/local/go/src/runtime/panic.go:890 +0x262
github.com/go-rod/rod/lib/utils.glob..func2({0x6eb4c0?, 0xc0000d4080?})
	/rod/lib/utils/utils.go:65 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/rod/lib/utils/utils.go:71
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc0001596c0?)
	/rod/lib/launcher/launcher.go:369 +0x67
github.com/go-rod/rod/lib/launcher.(*Manager).launch(0xc000060320, {0xa26bc0, 0xc00017a0e0}, 0xc000172200)
	/rod/lib/launcher/manager.go:173 +0x18a
github.com/go-rod/rod/lib/launcher.(*Manager).ServeHTTP(0xc000060320, {0xa26bc0, 0xc00017a0e0}, 0xc000172200)
	/rod/lib/launcher/manager.go:150 +0x7e
net/http.serverHandler.ServeHTTP({0xc000101800?}, {0xa26bc0, 0xc00017a0e0}, 0xc000172200)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0000014a0, {0xa27020, 0xc0001012c0})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

This is the output from running `main.go`:

```
panic: unexpected EOF

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x775be0?, 0xc0000120b0?})
	/home/v.arins/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/utils/utils.go:65 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	/home/v.arins/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/utils/utils.go:71
github.com/go-rod/rod/lib/cdp.MustStartWithURL({0xc3bfe0?, 0xc000025780?}, {0xc000018390?, 0xc0001961f0?}, 0xc0001823c0?)
	/home/v.arins/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/cdp/utils.go:34 +0x6e
github.com/go-rod/rod/lib/launcher.(*Launcher).MustClient(0xc00014c9a0)
	/home/v.arins/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/launcher/manager.go:73 +0x45
main.main()
	/home/v.arins/go/src/playground/main.go:30 +0x105
exit status 2
```

So I tried with previous versions of the go-rod image and it works with `v0.112.0` and older.

I think either a bug was introduced between `v0.112.0` and `v0.112.1`.

Or there is something different with latest version of chrome

Just in case it's relevant, here is my system information:

```
:~$ uname -a
Linux HRLL083 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

:~$ go version
go version go1.18.6 linux/amd64

:~$ docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by vitorarins** [comment]
Hi @ysmood, sorry to ping you here, but I am really curious about this as I want to use the latest version.
Thank you in advance for any feedback.

**Comment by vitorarins** [comment]
Thanks for taking the time. I also think it's a chrome/chromium issue.

Unfortunately running the container as you instructed doesn't give any output. And it exits right away:
```
v.arins:~$ docker run --rm ghcr.io/go-rod/rod:latest chrome --headless --no-sandbox --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
v.arins:~$
```

On `v0.112.0` however I get the following output:
```
v.arins:~$ docker run --rm ghcr.io/go-rod/rod:v0.112.0 chrome --headless --no-sandbox --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
[1208/150245.728132:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[1208/150245.728622:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory

DevTools listening on ws://0.0.0.0:9222/devtools/browser/887231ef-e99b-4ff0-880d-d00560715c5b
[1208/150245.795545:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[1208/150245.816146:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by ysmood** [comment]
Then I think it's a chromium issue, since the command use pure chromium without any other tool, rod is not involved. I'm not sure what I can help.

**Comment by khalilsarwari** [comment]
Can confirm, reverting to `v0.112.0` helped me resolve this issue.

**Comment by eussam** [comment]
Hi @ysmood , I'm new to Rod and when I try:

```
docker run --rm ghcr.io/go-rod/rod:latest chrome --headless --no-sandbox --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0
```

I get the output:

```
[dumb-init] chrome: No such file or directory
```

Any idea ?

**Comment by ysmood** [comment]
Thanks for the reporting, it should be fixed in the latest image, please pull and try again!

**Comment by philippefuentes** [comment]
Thank you for your quick fix. However now I get those errors in this output:

```
[0529/073310.333224:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0529/073310.423933:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0529/073310.423990:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0529/073310.439140:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[0529/073310.443334:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://0.0.0.0:9222/devtools/browser/15893832-a3ac-4347-80de-609437f32d97
```

**Comment by ysmood** [comment]
Those are just warnings.

**Comment by sheldondz** [comment]
We have this running too

```
[0725/065656.373941:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0725/065656.502933:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0725/065656.504265:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0725/065656.530675:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[0725/065656.540351:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.

DevTools listening on ws://0.0.0.0:9222/devtools/browser/b36423cc-bf44-4c30-8b8d-dea37e59c681
```

How do you connect to this remote instance via Launcher?
