### ISSUE TITLE
Cannot launch 2+ profiles from the one userDataDir

### ISSUE THREAD

**Issue by dataflowjs** [go-rod/rod#773]
Rod Version: v0.112.2

Hi.

```go
package main

import (
	"strconv"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func main() {

	for i := 0; i < 2; i++ {
		go func(index int) {
			profileIndex := strconv.Itoa(index)

			ln := launcher.NewUserMode()

			ctl := ln.
				Bin("C:/Program Files/Google/Chrome/Application/chrome.exe").
				Leakless(false).
				Headless(false).
				Set("user-data-dir", "C:/ChromeProfiles").
				Set("disable-web-security").
				Set("allow-running-insecure-content").
				Set("profile-directory", "Profile "+profileIndex).
				MustLaunch()

			for {
				browser := rod.New().
					ControlURL(ctl).
					SlowMotion(5 * time.Millisecond).
					NoDefaultDevice().
					MustConnect()

				browser.MustPage("https://example.com").MustSetWindow(50, 50, 800, 600)

				utils.Sleep(30)

				browser.Close()

				utils.Sleep(5)
			}
		}(i)

		utils.Sleep(1)
	}

	utils.Pause()

}

```

Trying to launch two profiles from the some user data dir and control it... but cant, why? maybe im do something wrong?

**Comment by dataflowjs** [comment]
Need to train some different profiles...

**Comment by dataflowjs** [comment]
How can i implement this behavior?

**Comment by dataflowjs** [comment]
i can launch to much profiles, but i wanna to control them

**Comment by ysmood** [comment]
I still don't understand your question, seems like your words are contradictory.

**Comment by dataflowjs** [comment]
Im publish minimal example thats not woriking
I have a folder ```userDataDir``` and i have some count of profiles in this folder and i wanna launch tham and control, but script not working, script just lauch one goorutine...

**Comment by dataflowjs** [comment]
sorry for english, trying to explain

**Comment by navicstein** [comment]
There's no need for `profile-directory` if it's going to be "Default", since you've already supplied `user-data-dir`   then it appends '\Default' to a specific dir

You can't have the same user profile running twice on the same chrome instance

**Comment by dataflowjs** [comment]
> There's no need for `profile-directory` if it's going to be "Default", since you've already supplied `user-data-dir` then it appends '\Default' to a specific dir
> 
> You can't have the same user profile running twice on the same chrome instance

I dont need run the some profile twice, im use it in loop, so every instance have different profile, but i cant launch them all via rod, but i can run all them directly
```go
for i := 0; i < profilesLen; i++ {
		profileIndex := strconv.Itoa(i)

		args := []string{
			`--user-data-dir=` + userDirPath,
			`--profile-directory=` + Config["PROFILE_DIR"] + ` ` + profileIndex,
			`--window-size=800,600`,
			`--remote-debugging-port=9223`,
		}

		args = append(args, Config["URL"])

		cmd := exec.Command("C:/Program Files/Google/Chrome/Application/chrome.exe", args...)

		err = cmd.Start()
		if err != nil {
			log.Println(err)
		}
	}
```

**Comment by ysmood** [comment]
Can you print the result of `launcher.FormatArgs` before `MustLaunch()`? You can compare the diff between rod and your manually args.

**Comment by dataflowjs** [comment]
> 

No difference... Trying to run again
```go
package main

import (
	"io"
	"log"
	"os"
	"strconv"
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
	"github.com/go-rod/rod/lib/utils"
)

func init() {
	file, e := os.OpenFile("file.log", os.O_CREATE|os.O_TRUNC|os.O_WRONLY|os.O_APPEND, 0666)
	if e != nil {
		log.Fatalln("Failed to open log file")
	}

	multi := io.MultiWriter(file, os.Stdout)
	log.SetOutput(multi)
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}

func main() {
	for i := 10; i < 13; i++ {
		go func(index int) {
			iStr := strconv.Itoa(index)

			ln := launcher.NewUserMode().
				Bin("C:/Program Files/Google/Chrome/Application/chrome.exe").
				Leakless(false).
				Headless(false).
				Set("--user-data-dir", `profiles`).
				Set("--profile-directory", `Profile`+iStr+``).
				Set("--remote-debugging-port", `100`+iStr+``)
			log.Println(ln.FormatArgs())

			ctl := ln.MustLaunch()

			browser := rod.New().
				ControlURL(ctl).
				SlowMotion(5 * time.Millisecond).
				NoDefaultDevice().
				MustConnect()

			page := browser.MustPage("https://example.com").MustSetWindow(50, 50, 800, 600)
			_ = page

			utils.Pause()
		}(i)
		utils.Sleep(2)
	}
	utils.Pause()
}
```

and i got this error

```
2023/01/04 08:37:02 main.go:140: [--no-startup-window --profile-directory=Profile10 --remote-debugging-port=10010 --user-data-dir=E:\w\go\src\github.com\imbaMF\launcher\profiles]
2023/01/04 08:37:04 main.go:140: [--no-startup-window --profile-directory=Profile11 --remote-debugging-port=10011 --user-data-dir=E:\w\go\src\github.com\imbaMF\launcher\profiles]
2023/01/04 08:37:06 main.go:140: [--no-startup-window --profile-directory=Profile12 --remote-debugging-port=10012 --user-data-dir=E:\w\go\src\github.com\imbaMF\launcher\profiles]
panic: [launcher] Failed to get the debug url: ���� ��� ������� ��������� � ������� ������ ��������.


goroutine 36 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xbf8bc0?, 0xc0000885e0?})
        E:/w/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/utils/utils.go:65 +0x25
github.com/go-rod/rod/lib/utils.E(...)
        E:/w/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/utils/utils.go:71
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000119f30?)
        E:/w/go/pkg/mod/github.com/go-rod/rod@v0.112.2/lib/launcher/launcher.go:369 +0x67
main.main.func1(0x0?)
        E:/w/go/src/github.com/imbaMF/launcher/main.go:142 +0x234
created by main.main
        E:/w/go/src/github.com/imbaMF/launcher/main.go:127 +0xe8
```

**Comment by dataflowjs** [comment]
and i was trying without ```--no-startup-window``` flag, result the some

**Comment by dataflowjs** [comment]
and if i do without loop, it works

```go
	go func() {

		ln := launcher.NewUserMode().
			Bin("C:/Program Files/Google/Chrome/Application/chrome.exe").
			Leakless(false).
			Headless(false).
			// UserDataDir(`C:/Chrome/Profiles`).
			Set("--user-data-dir", `profiles`).
			Set("--profile-directory", `Profile10`).
			Set("--remote-debugging-port", `10010`).
			Delete("--no-startup-window")
		// RemoteDebuggingPort(9992 + index)
		// ProfileDir(`"Profile ` + iStr + `"`)
		log.Println(ln.FormatArgs())

		ctl := ln.MustLaunch()

		browser := rod.New().
			ControlURL(ctl).
			SlowMotion(5 * time.Millisecond).
			NoDefaultDevice().
			MustConnect()

		page := browser.MustPage("https://example.com").MustSetWindow(50, 50, 800, 600)
		_ = page

		utils.Pause()
	}()

	utils.Pause()
```

why i cannot open them in loop?

**Comment by ysmood** [comment]
Seems like a single `--user-data-dir` only allow a single `--remote-debugging-port`, you can't share it with multiple controllers.

**Comment by dataflowjs** [comment]
Hi, becouse rod cannot working with multiple user-data-dir on windows 10, dont know about linux/mac

**Comment by ysmood** [comment]
Works fine to me on Windows
