### ISSUE TITLE
MustIncognito causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by NuLL3rr0r** [go-rod/rod#785]
Rod Version: v0.112.2

## The code to demonstrate your question

```go
// This is the template to demonstrate how to test Rod.
func TestRod(t *testing.T) {
	userDataDir := filepath.Join(os.TempDir(), fmt.Sprintf("bot-%s", "some-name"))

	url := launcher.New().
		UserDataDir(userDataDir).
		Proxy("127.0.0.1:8080").
		WorkingDir("").
		Devtools(false).
		Headless(false)

	_ = rod.New().
		ControlURL(url.MustLaunch()).
		MustIncognito().
		NoDefaultDevice()
}
```

## What you got

Such as what error you see.

```
parallel test 16
--- FAIL: TestRod (0.21s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x76c24e]

goroutine 72 [running]:
testing.tRunner.func1.2({0x863800, 0xfe3100})
	/usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x863800, 0xfe3100})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/go-rod/rod.(*Browser).Call(0xc00012c000, {0xd5e650?, 0xc000030120?}, {0x0, 0x0}, {0x9257db, 0x1b}, {0x8dff00, 0xc00013a080})
	/home/mamadou/dev/rod/browser.go:235 +0x6e
github.com/go-rod/rod/lib/proto.call({0x9257db, 0x1b}, {0x8dff00, 0xc00013a080}, {0x8322e0?, 0xc0005320f0}, {0xd5a760, 0xc00012c000})
	/home/mamadou/dev/rod/lib/proto/a_interface.go:63 +0x111
github.com/go-rod/rod/lib/proto.TargetCreateBrowserContext.Call(...)
	/home/mamadou/dev/rod/lib/proto/target.go:240
github.com/go-rod/rod.(*Browser).Incognito(0xc00012c000?)
	/home/mamadou/dev/rod/browser.go:82 +0xe5
github.com/go-rod/rod.(*Browser).MustIncognito(0xc00012c000)
	/home/mamadou/dev/rod/must.go:62 +0x25
github.com/go-rod/rod_test.TestRod(0x0?)
	/home/mamadou/dev/rod/rod_test.go:26 +0x1b2
testing.tRunner(0xc000103a00, 0xbb1340)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f
exit status 2
FAIL	github.com/go-rod/rod	6.570s
```

## What you expected to see

The browser window is in incognito mode.

## What have you tried to solve the question

Nothing.

**Comment by NuLL3rr0r** [comment]
I have to mention if I replace MustIncognito with MustConnect it runs fine.

**Comment by NuLL3rr0r** [comment]
I've also noticed if I run it like this, it runs and claims it's in Incognito mode, which clearly is not. I'll post screenshots of what I mean.

```go
	browser := rod.New().
		ControlURL(url.MustLaunch()).
		MustConnect().
		MustIncognito().
		NoDefaultDevice()

```

**Comment by NuLL3rr0r** [comment]
OK, as it can be seen in the screenshots, when I try to navigate to Twitter using go-rod, Twitter says: "Something went wrong, but don’t fret — let’s give it another shot.". I am sure they do it on purpose. When I manually click on the Incognito mode and open the URL it opens fine.

As you can see in the sample I create a new UserDataDir, so there should be no cookies stored. I am not sure how Twitter is able to track it down. Maybe rod shares cookies between instances?

So there are three issues here:

1. Twitter detects Rod somehow, though I use the stealth library as well
2. Rod probably shares cookies between instances? Not sure.
3. The Incognito mode using the above
![Screenshot_2022-12-30_18_07_39_674099832](https://user-images.githubusercontent.com/2454895/210095980-28f96be2-2472-45c2-a6bc-af7c0412fc4d.png)
 code is not True Incognito Mode, just a false cl
![Screenshot_2022-12-30_18_07_13_226066356](https://user-images.githubusercontent.com/2454895/210095969-7e40beaf-17d1-46b0-b4a3-ea1be6822379.png)
aim.

**Comment by ysmood** [comment]
Could you change the title of the issue to a more proper one.

**Comment by NuLL3rr0r** [comment]
I hope that is good enough.

**Comment by NuLL3rr0r** [comment]
Just to provide an update. I've figured if I use Brave instead of the default browser provided by go-rod it actually works.

This is from a working project:
```
	url := launcher.New().
		Bin("/usr/bin/brave-bin").
		UserDataDir(userDataDir).
		Proxy(proxy).
		WorkingDir("").
		Devtools(false).
		Headless(false)

	browser := rod.New().
		ControlURL(url.MustLaunch()).
		MustConnect().
		NoDefaultDevice()
```

If I remove the `Bin("/usr/bin/brave-bin").` part, it would be the same thing.

**Comment by ysmood** [comment]
Then it sounds like a upstream issue. Brave seems like a good alternative for anti-fingerprinting.
