### ISSUE TITLE
how to use JSSelector like chromedp

### ISSUE THREAD

**Issue by zhangguanzhang** [go-rod/rod#88]
in chromedp
```
chromedp.WaitVisible(`document.querySelector("#userName")`, chromedp.ByJSPath),
```
in rod, will panic:
```
	page := browser.Page("http://xxxxx/user/login")
	page.ElementByJS(`document.querySelector("#userName")`).
		WaitVisible()
```
panic info:
```
D:\golang\go\lesson>go run main.go
panic: [rod] eval error
TypeError: Cannot read property 'apply' of null
    at <anonymous>:1:60

goroutine 1 [running]:
github.com/ysmood/kit/pkg/utils.E(0xc0001fa720, 0x1, 0x1, 0x0, 0xd93364, 0x23)
        D:/golang/GOPATH/pkg/mod/github.com/ysmood/kit@v0.24.4/pkg/utils/utils.go:33 +0xb2
github.com/go-rod/rod.(*Page).ElementByJS(0xc0002b6480, 0xd93364, 0x23, 0x0, 0x0, 0x0, 0xc0000260b8)
        D:/golang/GOPATH/pkg/mod/github.com/go-rod/rod@v0.43.1/sugar.go:345 +0x12e
main.main()
        D:/golang/go/lesson/main.go:16 +0x1bc
exit status 2

```

**Comment by zhangguanzhang** [comment]
and this js this don't work
```
page.Eval(`() => document.getElementById('iframe').contentWindow.document.querySelector('div[class^=ckplayer] video').click()`)
```
it could run ok at the browser console

**Comment by ysmood** [comment]
do you see the link in the err message? please read it. it already tells you what to do. just click any where in the browser, don't use js to click, use Rod's click method. why? to prevent evil sites playing video automatically

**Comment by zhangguanzhang** [comment]
就是播放视频的，我用iframe做到了，2楼和3楼的信息请忽略。主要是1楼的js选择器如何使用

**Comment by ysmood** [comment]
page.ElementByJS(`() => document.querySelector("#userName")`)

看看 ElementByJS 的 ide 提示，说的很清楚了，要传js函数。这么设计是为了跨语言传参数：

```go
page.Eval(`(a) => console.log(a)`, 10)
```

**Comment by zhangguanzhang** [comment]
我以为直接传js的代码
