### ISSUE TITLE
Is enabling the `Use Rosetta` option in Docker for Mac the correct solution for resolving panic with docker?

### ISSUE THREAD

**Issue by goldeneggg** [go-rod/rod#914]
Rod Version: v0.114.2

OS X Version: 13.5 (Ventura)

Docker for Mac: 4.21.1 (114176), Engine: 24.0.2

## The code to demonstrate your question

1. Launch rod browser with docker

    ```bash
    docker run -p 7317:7317 ghcr.io/go-rod/rod
    ```

1. Clone Rod to your local and cd to the repository and run example of `launch-managed`:

    ```bash
    git clone https://github.com/go-rod/rod
    cd lib/examples/launch-managed/
    go run main.go
    ```

## What you got

I got a panic `panic: unexpected EOF`

Logs of `go run main.go` console as follows

```
panic: unexpected EOF

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x102a5c020?, 0x1400010a070?})
        /Users/xxx/go/pkg/mod/github.com/go-rod/rod@v0.114.2/lib/utils/utils.go:68 +0x24
github.com/go-rod/rod/lib/utils.E(...)
        /Users/xxx/go/pkg/mod/github.com/go-rod/rod@v0.114.2/lib/utils/utils.go:74
github.com/go-rod/rod/lib/cdp.MustStartWithURL({0x102b0f660?, 0x1400009d130?}, {0x140000ec1b0?, 0x0?}, 0x140000242c0?)
        /Users/xxx/go/pkg/mod/github.com/go-rod/rod@v0.114.2/lib/cdp/utils.go:34 +0x70
github.com/go-rod/rod/lib/launcher.(*Launcher).MustClient(0x140001ad500)
        /Users/xxx/go/pkg/mod/github.com/go-rod/rod@v0.114.2/lib/launcher/manager.go:78 +0x50
main.main()
        /Users/xxx/rod/lib/examples/launch-managed/main.go:30 +0xfc
exit status 2
```

Logs of `docker run -p 7317:7317 ghcr.io/go-rod/rod` console as follows

```
% docker run -p 7317:7317 ghcr.io/go-rod/rod
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[rod-manager] listening on: [::]:7317
[launcher.Browser]2023/08/05 03:13:22 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1131003/chrome-linux.zip
[launcher.Browser]2023/08/05 03:13:22 Progress: 00%
[launcher.Browser]2023/08/05 03:13:23 Progress: 14%
[launcher.Browser]2023/08/05 03:13:24 Progress: 37%
[launcher.Browser]2023/08/05 03:13:25 Progress: 57%
[launcher.Browser]2023/08/05 03:13:26 Progress: 79%
[launcher.Browser]2023/08/05 03:13:27 Unzip: /root/.cache/rod/browser/chromium-1131003
[launcher.Browser]2023/08/05 03:13:27 Progress: 00%
[launcher.Browser]2023/08/05 03:13:28 Progress: 07%
[launcher.Browser]2023/08/05 03:13:29 Progress: 12%
[launcher.Browser]2023/08/05 03:13:30 Progress: 17%
[launcher.Browser]2023/08/05 03:13:31 Progress: 22%
[launcher.Browser]2023/08/05 03:13:32 Progress: 27%
[launcher.Browser]2023/08/05 03:13:33 Progress: 32%
[launcher.Browser]2023/08/05 03:13:34 Progress: 36%
[launcher.Browser]2023/08/05 03:13:35 Progress: 41%
[launcher.Browser]2023/08/05 03:13:36 Progress: 46%
[launcher.Browser]2023/08/05 03:13:37 Progress: 55%
[launcher.Browser]2023/08/05 03:13:38 Progress: 65%
[launcher.Browser]2023/08/05 03:13:39 Progress: 74%
[launcher.Browser]2023/08/05 03:13:40 Progress: 80%
[launcher.Browser]2023/08/05 03:13:41 Progress: 88%
[launcher.Browser]2023/08/05 03:13:42 Progress: 97%
[launcher.Browser]2023/08/05 03:13:42 Downloaded: /root/.cache/rod/browser/chromium-1131003
2023/08/05 03:13:47 http: panic serving 172.17.0.1:60712: [launcher] Failed to get the debug url: [0805/031343.576579:ERROR:stack_trace_posix.cc(811)] Failed to parse the contents of /proc/self/maps
[0805/031344.756508:ERROR:stack_trace_posix.cc(811)] Failed to parse the contents of /proc/self/maps
[0805/031344.757112:ERROR:stack_trace_posix.cc(811)] Failed to parse the contents of /proc/self/maps
[94:94:0805/031344.793093:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
#0 0x004007de8c52 base::debug::CollectStackTrace()
#1 0x004007dd55f3 base::debug::StackTrace::StackTrace()
#2 0x004007d26404 logging::LogMessage::~LogMessage()
#3 0x004007d26e4e logging::LogMessage::~LogMessage()
#4 0x004007d10e27 logging::CheckError::~CheckError()
#5 0x0040072810bf content::ZygoteMain()
#6 0x00400727a1e6 content::RunZygote()
#7 0x00400727b0b2 content::RunOtherNamedProcessTypeMain()
#8 0x00400727c411 content::ContentMainRunnerImpl::Run()
#9 0x004007279b6c content::RunContentProcess()
#10 0x004007279cd6 content::ContentMain()
#11 0x00400399d309 ChromeMain
#12 0x004010e58d90 <unknown>
#13 0x004010e58e40 __libc_start_main
#14 0x00400399d02a _start
Crash keys:
  "switch-6" = "--change-stack-guard-on-fork=enable"
  "switch-5" = "--user-data-dir=/tmp/rod/user-data/6e1f5e01ef97059b"
  "switch-4" = "--enable-crash-reporter=,"
  "switch-3" = "--crashpad-handler-pid=84"
  "switch-2" = "--no-sandbox"
  "switch-1" = "--no-zygote-sandbox"
  "num-switches" = "7"

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[0805/031345.141052:FATAL:nacl_helper_linux.cc(480)] Check failed: nacl_sandbox->IsSingleThreaded().
#0 0x0040002ddce2 base::debug::CollectStackTrace()
#1 0x0040002d89c3 base::debug::StackTrace::StackTrace()
#2 0x004000282194 logging::LogMessage::~LogMessage()
#3 0x004000282bde logging::LogMessage::~LogMessage()
#4 0x004000279a47 logging::CheckError::~CheckError()
#5 0x00400019fa50 main
#6 0x004001eaad90 <unknown>
#7 0x004001eaae40 __libc_start_main
#8 0x00400019ebaa _start

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[96:96:0805/031345.321359:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
[96:96:0805/031345.322463:FATAL:zygote_main_linux.cc(145)] Check failed: sandbox::ThreadHelpers::IsSingleThreaded().
#0 0x004007de8c52 base::debug::CollectStackTrace()
#1 0x004007dd55f3 base::debug::StackTrace::StackTrace()
#2 0x004007d26404 logging::LogMessage::~LogMessage()
#3 0x004007d26e4e logging::LogMessage::~LogMessage()
#4 0x004007d10e27 logging::CheckError::~CheckError()
#5 0x0040072810bf content::ZygoteMain()
#6 0x00400727a1e6 content::RunZygote()
#7 0x00400727b0b2 content::RunOtherNamedProcessTypeMain()
#8 0x00400727c411 content::ContentMainRunnerImpl::Run()
#9 0x004007279b6c content::RunContentProcess()
#10 0x004007279cd6 content::ContentMain()
#11 0x00400399d309 ChromeMain
#12 0x004010e58d90 <unknown>
#13 0x004010e58e40 __libc_start_main
#14 0x00400399d02a _start
Crash keys:
  "switch-5" = "--change-stack-guard-on-fork=enable"
  "switch-4" = "--user-data-dir=/tmp/rod/user-data/6e1f5e01ef97059b"
  "switch-3" = "--enable-crash-reporter=,"
  "switch-2" = "--crashpad-handler-pid=84"
  "switch-1" = "--no-sandbox"
  "num-switches" = "6"

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
[79:105:0805/031345.889118:ERROR:file_path_watcher_inotify.cc(315)] inotify_init() failed: Function not implemented (38)
[79:108:0805/031345.911882:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0805/031345.979097:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)

goroutine 34 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x70f4e0, 0xc0001dcc90})
        /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/go-rod/rod/lib/utils.glob..func2({0x70f4e0?, 0xc0001dcc90?})
        /rod/lib/utils/utils.go:68 +0x25
github.com/go-rod/rod/lib/utils.E(...)
        /rod/lib/utils/utils.go:74
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc00022c070?)
        /rod/lib/launcher/launcher.go:368 +0x67
github.com/go-rod/rod/lib/launcher.(*Manager).launch(0xc0001342e0, {0xa4cdf0, 0xc000238000}, 0xc00022a000)
        /rod/lib/launcher/manager.go:184 +0x18a
github.com/go-rod/rod/lib/launcher.(*Manager).ServeHTTP(0xc0001342e0, {0xa4cdf0, 0xc000238000}, 0xc00022a000)
        /rod/lib/launcher/manager.go:161 +0x7e
net/http.serverHandler.ServeHTTP({0xc000204090?}, {0xa4cdf0, 0xc000238000}, 0xc00022a000)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000208000, {0xa4d088, 0xc00011b3e0})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

## What you expected to see

I expect working correctly.
(I don't remember the exact version, but it was working correctly at least 6 months ago)

## What have you tried to solve the question

1. Run `docker run` command with `--platform linux/x86_64` option
    - I could not resolve
1. Enable `Use Rosetta for x86/amd64 emulation on Apple Silicon` option of Docker for Mac (screen shot as follows)
    - __I could resolve__

![docker-for-mac-rosetta](https://github.com/go-rod/rod/assets/994282/9bcc0c70-e33c-4a73-90d5-523136ed1462)

Is this the correct solution for this problem?

**Comment by ysmood** [comment]
I use Apple M2 macbook, works fine to me.

**Comment by goldeneggg** [comment]
> rod docker image has arm version.

After deleting the existing amd64 docker image and doing a docker pull again to get the arm64 image again, the problem was resolved.
thank you.
