### ISSUE TITLE
method ` Test/TestGetDownloadFileWithHijack` occasionally goes wrong

### ISSUE THREAD

**Issue by zhangguanzhang** [go-rod/rod#92]
in `Test / others (macos-latest)`
```
=== RUN   Test/TestGetDownloadFileWithHijack
[2020-07-05 11:33:44] {"code":-32000,"message":"Fetch domain is not enabled","data":""} 
goroutine 170 [running]:
runtime/debug.Stack(0xbfb88c86310b63b0, 0x27b41c65f, 0x2406220)
	/Users/runner/hostedtoolcache/go/1.14.4/x64/src/runtime/debug/stack.go:24 +0x9d
github.com/ysmood/kit/pkg/utils.Err(0xc00063f6b0, 0x1, 0x1)
	/Users/runner/go/pkg/mod/github.com/ysmood/kit@v0.24.4/pkg/utils/log.go:45 +0x67
github.com/go-rod/rod.(*HijackRouter).new.func1(0x1d51400, 0xc000670d80)
	/Users/runner/runners/2.169.1/work/rod/rod/hijack.go:161 +0x85
github.com/go-rod/rod.(*HijackRouter).initEvents.func1.1(0xc0001d0910, 0xc00007a180)
	/Users/runner/runners/2.169.1/work/rod/rod/hijack.go:79 +0x253
created by github.com/go-rod/rod.(*HijackRouter).initEvents.func1
	/Users/runner/runners/2.169.1/work/rod/rod/hijack.go:58 +0x48

 
```

**Comment by ysmood** [comment]
I will look into it, the github CI is not stable 😂

**Comment by zhangguanzhang** [comment]
maybe could use the travis-ci

**Comment by ysmood** [comment]
I just switched from travis from github. Currently, even consider the bugs of github ci it's still more appealing than travis.
And travis' Windows support is way worse than github's (github is a Microsoft company).
