### ISSUE TITLE
请教,论坛摇摇乐场景下程序会panic怎么解决

### ISSUE THREAD

**Issue by lakevilladom** [go-rod/rod#934]
Rod Version: v0.114.3

```go
package main

import (
	"log"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func t() {
	ur1 := `https://www.zhsan2.top/plugin.php?id=yinxingfei_zzza:yinxingfei_zzza_hall`
	wsUrl := launcher.MustResolveURL("127.0.0.1:9222")
	u := rod.New().ControlURL(wsUrl).MustConnect()
	p := u.MustPage(ur1)
	defer p.Close()

	wait := p.MustWaitRequestIdle()
	p.MustElement(`div.zzza_button_1`).MustClick()
	p.MustElement(`div.yyl-random-result`).MustWaitVisible()
	wait()
	log.Println("摇一摇成功:", p.MustElement(`div.yyl-random-result p`).MustText())
}
```

随便找了一个有摇摇乐场景的论坛，代码是在`p.MustElement("div.yyl-random-result").MustWaitVisible()` panic的，大致报错如下：
```
[rod] 2023/09/01 16:58:36 [query] rod.element("div.yyl-random-result")  <page:F629137E>
[rod] 2023/09/01 16:58:36 [wait] visible <div.yyl-random-result>
[rod] 2023/09/01 16:58:37 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:38 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:39 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:40 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:41 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:42 [wait requests] <page:F629137E> map[]
[rod] 2023/09/01 16:58:43 [wait requests] <page:F629137E> map[]
panic: cannot find object: {"type":"object","subtype":"node","className":"HTMLDivElement","value":null,"description":"div.yyl-random-result","objectId":"268143539731550612.2.22"}

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x11eaf00?, 0xc00029a090?})
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/lib/utils/utils.go:68 +0x25
github.com/go-rod/rod.genE.func1({0xc00028b2b0?, 0x4?, 0x0?})
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/must.go:37 +0x5a
github.com/go-rod/rod.(*Element).MustWaitVisible(0xc000347020)
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/must.go:936 +0x89
main.t()
        E:/CodeSpace/05Program/Rod_PanLe/t.go:19 +0x16a
main.main()
        E:/CodeSpace/05Program/Rod_PanLe/main.go:72 +0x13c
exit status 2
```

> 说明：这个摇摇乐必须等待摇到的结果显示后，才有效，所以需要等待结果显示，但是等待过程中页面好像重新加载，然后就报错了

**Comment by ysmood** [comment]
WaitStable

**Comment by lakevilladom** [comment]
```go
p.MustElement(`div.yyl-random-result`).MustWaitStable()
```
刚才试了，任然报错，应该是bug
补充下，`div.yyl-random-result`这个元素在MustPage()后就存在了，只是style='display:none',随着`p.MustElement(`div.zzza_button_1`).MustClick()` 这个点击以后约有2秒后，页面刷新后就报错了

```
[rod] 2023/09/01 19:26:23 [wait requests] <page:E4A6BEE7> map[]
panic: cannot find object: {"type":"object","subtype":"node","className":"HTMLDivElement","value":null,"description":"div.yyl-random-result","objectId":"-6067538385831466795.2.22"}

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xe1bf00?, 0xc000232928?})
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/lib/utils/utils.go:68 +0x25
github.com/go-rod/rod.genE.func1({0xc00032fcd0?, 0x4?, 0x0?})
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/must.go:37 +0x5a
github.com/go-rod/rod.(*Element).MustWaitStable(0xc00011a5a0)
        E:/CodeSpace/00GoMod/pkg/mod/github.com/go-rod/rod@v0.114.3/must.go:924 +0x8b
main.t()
        E:/CodeSpace/05Program/Rod_PanLe/t.go:19 +0x16a
```

**Comment by lakevilladom** [comment]
@ysmood

**Comment by ysmood** [comment]
你可以不使用 Must 函数，这种情况 rod 是无法保证的，就比如你在操纵页面里的一个元素，它突然就被页面里的 js 删除了，你怎么办？

你使用 p.Element 局可以捕捉到这个错误自己处理了。
