### ISSUE TITLE
How to ignore cert errors when HijackRequests is used?

### ISSUE THREAD

**Issue by CyberStryk** [go-rod/rod#990]
Rod Version: v0.114.0

## The code to demonstrate your question  

```go
package main

import (
        "fmt"
        "github.com/go-rod/rod"
)

func HijackViaPage() {
        browser := rod.New().MustConnect().MustIgnoreCertErrors(true)
        page := browser.MustPage("")

        fmt.Println("Running NON-Hijacked MustNavigate.")

        // NO PANIC.
        page.MustNavigate("https://127.0.0.1/")

        router := page.HijackRequests()

        router.MustAdd("*", func(ctx *rod.Hijack) {
                ctx.Request.Req().Host = "test.host"

                // PANIC: Certificate issue.
                ctx.MustLoadResponse()
        })

        go router.Run()
        fmt.Println("Running NON-Hijacked MustNavigate.")
        // PANIC: Certificate Errors (Self Signed)
        page.MustNavigate("https://127.0.0.1/")

}

func main() {
        HijackViaPage()
}
          
```

## What you got  

MustNavigate ignores certificate errors and works as expected when not using hijack.
MustNavigate does not ignore cert errors and panics when it is hijacked.

```bash
└─$ go build && ./vhost-screenshot
Running NON-Hijacked MustNavigate.
Running hijacked MustNavigate.
panic: Get "https://127.0.0.1/": tls: failed to verify certificate: x509: certificate signed by unknown authority

goroutine 26 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x7bd340?, 0xc0002d9f80?})
	/home/user/go/pkg/mod/github.com/go-rod/rod@v0.114.0/lib/utils/utils.go:68 +0x1d
main.HijackViaPage.New.(*Browser).WithPanic.genE.func2({0xc00032e190?, 0x0?, 0x1?})
	/home/user/go/pkg/mod/github.com/go-rod/rod@v0.114.0/must.go:36 +0x5a
github.com/go-rod/rod.(*Hijack).MustLoadResponse(0xc00009c580)
	/home/user/go/pkg/mod/github.com/go-rod/rod@v0.114.0/must.go:1121 +0x8f
main.HijackViaPage.func1(0x0?)
	/home/user/development/vhost-screenshot/vhost-screenshot.go:24 +0x13
github.com/go-rod/rod.(*HijackRouter).initEvents.func1.1()
	/home/user/go/pkg/mod/github.com/go-rod/rod@v0.114.0/hijack.go:77 +0x122
created by github.com/go-rod/rod.(*HijackRouter).initEvents.func1 in goroutine 36
	/home/user/go/pkg/mod/github.com/go-rod/rod@v0.114.0/hijack.go:70 +0xaa
```

## What you expect to see  

I expect both page.MustNavigate("https://127.0.0.1") to ignore cert errors and to work without "panic ".

## What have you tried to solve the question

I have tried use using both Browser and Page hijack. Both fail at the same spot. I also tried modifying hijack.go to attempt to manually set MustIgnoreCertErrors(true) in every function that uses the browser. I still got cert errors in the same place.

**Comment by DC3x6** [comment]
```
        router := browser.HijackRequests()
	defer router.MustStop()
	router.MustAdd("*", func(ctx *rod.Hijack) {
		println(ctx.Request.Type(), ctx.Request.URL().String(), ctx.Request.Event().RequestID)
		ctx.ContinueRequest(&proto.FetchContinueRequest{})
		ctx.LoadResponse(&http.Client{
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{
					InsecureSkipVerify: true,
				},
			},
		}, true)
	})
	go router.Run()
```

默认的是http.DefaultClient
```
func (h *Hijack) MustLoadResponse() {
	h.browser.e(h.LoadResponse(http.DefaultClient, true))
}
```
修改成自定义的http.Client即可

**Comment by CyberStryk** [comment]
Perfect!  Thank you for your time! 

My full code for anyone looking at this issue later.

```
func HijackViaPage() {
	browser := rod.New().MustConnect().MustIgnoreCertErrors(true)
	page := browser.MustPage("")

	// THIS WORKS, No issues.
	page.MustNavigate("https://127.0.0.1/")

	router := page.HijackRequests()

	router.MustAdd("*", func(ctx *rod.Hijack) {

		// Ignore certificate errors and fetch page.
		ctx.LoadResponse(&http.Client{
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{
					InsecureSkipVerify: true,
				},
			},
		}, true)
	})

	go router.Run()
	page.MustNavigate("https://127.0.0.1")
```

**Comment by CyberStryk** [comment]
Closing as answered.
